#define plamen_broker_v2_specialized_worker_launch_derive_apple plamen_test_real_worker_launch_derive_apple_unused
#define plamen_broker_v2_specialized_worker_request_build plamen_test_real_worker_request_build_unused
#define plamen_broker_v2_specialized_worker_terminal_parse plamen_test_real_worker_terminal_parse_unused
#include "../darwin/plamen_broker_v2_specialized_request.c"
