"""Reviewed role-8/9 operation-4 assets for Medusa and solc-amd64.

This is the only renderer for the checked-in semantic receipt prefixes and
runtime source manifests below.  It validates reviewed JSON and projects
exact bytes, but it never acquires an upstream object, verifies Sigstore,
extracts an archive, appends a producer footer, or issues authority.  Those
effects belong to the signed native source-bootstrap coordinator.
"""

from __future__ import annotations

from dataclasses import dataclass
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys
from typing import Any, NoReturn

import medusa_release_policy as medusa


NEXT_REQUIRED_AUTHORITY = "PLAMEN_NATIVE_SOURCE_BOOTSTRAP_COORDINATOR_RECEIPT_V1"
RENDERER_SCHEMA = "plamen.native-evm-static-acquisition-renderer.v1"
RENDERER_PATH = "scripts/native_evm_static_acquisition_assets.py"
SOURCE_MANIFEST_SCHEMA = "plamen.runtime_source_manifest.native-retained.v1"
AUTHENTICATION_SCOPE = "NATIVE_RETAINED_SOURCE_INPUT"
PRODUCER_FOOTER_SIZE = 512
STATIC_PAYLOAD_IDENTITY_MODE = 1

SOLC_POLICY_PATH = "verification_policy/solc_amd64_acquisition.v1.json"
SOLC_POLICY_SHA256 = "f08a1ce15fc990a296f39bb8736cf31d55a1708201d4765e51752dcc86414d68"
SOLC_POLICY_SIZE = 1473
MANAGED_EVM_POLICY_PATH = "verification_policy/managed_evm_python_toolchain.v1.json"
MANAGED_EVM_POLICY_SHA256 = "c4091eeadb398b17bd36dbfd88358d06a6bb2b7976ad20f75a37183a9e2e93b5"
MANAGED_EVM_POLICY_SIZE = 98_761

_HEX64 = re.compile(r"[0-9a-f]{64}\Z")


class NativeEVMStaticAcquisitionError(RuntimeError):
    """A reviewed role-8/9 input or generated byte contract differs."""


@dataclass(frozen=True, slots=True)
class RoleContract:
    role: str
    ordinal: int
    receipt_validator: int
    policy_path: str
    policy_sha256: str
    policy_size: int
    receipt_path: str
    receipt_schema: str
    receipt_sha256: str
    receipt_size: int
    source_manifest_path: str
    source_manifest_sha256: str
    source_manifest_size: int
    artifact_id: str
    version: str
    platform: str
    payload_sha256: str
    payload_size: int
    install_path: str
    source_reference: str


MEDUSA = RoleContract(
    role="medusa", ordinal=8, receipt_validator=6,
    policy_path=medusa.POLICY_PATH, policy_sha256=medusa.POLICY_SHA256,
    policy_size=1696,
    receipt_path="verification_policy/medusa_acquisition_receipt.v1.json",
    receipt_schema="plamen.medusa-acquisition-receipt.v1",
    receipt_sha256="208b814ab650db58fb326d58930ae5db47162905a938e6c3532d9d6ff18a7f97",
    receipt_size=1237,
    source_manifest_path="verification_policy/medusa_runtime_source_manifest.v1.json",
    source_manifest_sha256="3353512eebb22a052ba2e5a87c2fe86055381b729498df3299b4d36dedf09260",
    source_manifest_size=555,
    artifact_id="medusa-1.5.1-linux-x64", version="1.5.1",
    platform="linux/amd64", payload_sha256=medusa.EXECUTABLE_SHA256,
    payload_size=medusa.EXECUTABLE_SIZE, install_path=medusa.INSTALL_PATH,
    source_reference=(
        "https://github.com/crytic/medusa/releases/download/v1.5.1/"
        "medusa-linux-x64.tar.gz"
    ),
)

SOLC_AMD64 = RoleContract(
    role="solc_amd64", ordinal=9, receipt_validator=7,
    policy_path=SOLC_POLICY_PATH, policy_sha256=SOLC_POLICY_SHA256,
    policy_size=SOLC_POLICY_SIZE,
    receipt_path="verification_policy/solc_amd64_acquisition_receipt.v1.json",
    receipt_schema="plamen.solc-amd64-acquisition-receipt.v1",
    receipt_sha256="9eebf95c0a0eceaf853f30419b9d71abde65c594dad0666619d86c022c9eb39c",
    receipt_size=1341,
    source_manifest_path="verification_policy/solc_amd64_runtime_source_manifest.v1.json",
    source_manifest_sha256="bb013be7af35e8df4ff900521a4859100af71a0b9c460777877768c5ddee8b9b",
    source_manifest_size=596,
    artifact_id="solc-0.8.26-commit.8a97fa7a-linux-amd64",
    version="0.8.26+commit.8a97fa7a", platform="linux/amd64",
    payload_sha256="d5f23436f443edb85d8e76906d12f0a86ce0490e7663a9e608efeb7a93f149ef",
    payload_size=15_434_456,
    install_path="/usr/local/lib/plamen/toolchains/solc-amd64/solc",
    source_reference=(
        "https://binaries.soliditylang.org/linux-amd64/"
        "solc-linux-amd64-v0.8.26+commit.8a97fa7a"
    ),
)

CONTRACTS = {item.role: item for item in (MEDUSA, SOLC_AMD64)}


def _fail(message: str) -> NoReturn:
    raise NativeEVMStaticAcquisitionError(message) from None


def _pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if type(key) is not str or key in result:
            _fail("acquisition JSON contains a duplicate/non-string key")
        result[key] = value
    return result


def _canonical(value: Any, *, final_lf: bool) -> bytes:
    try:
        raw = json.dumps(
            value, sort_keys=True, separators=(",", ":"), ensure_ascii=True,
            allow_nan=False,
        ).encode("ascii")
    except (TypeError, ValueError, UnicodeError):
        _fail("acquisition JSON is not canonicalizable")
    return raw + (b"\n" if final_lf else b"")


def _decode_exact(
    raw: bytes, *, digest: str, size: int, label: str, final_lf: bool,
    canonical: bool = True,
) -> dict[str, Any]:
    if (
        type(raw) is not bytes or len(raw) != size
        or _HEX64.fullmatch(digest) is None
        or hashlib.sha256(raw).hexdigest() != digest
    ):
        _fail(f"{label} exact bytes differ")
    try:
        value = json.loads(
            raw.decode("ascii", "strict"), object_pairs_hook=_pairs,
            parse_constant=lambda token: _fail(f"{label} contains {token}"),
        )
    except (UnicodeError, json.JSONDecodeError):
        _fail(f"{label} is not strict JSON")
    if type(value) is not dict or (
        canonical and raw != _canonical(value, final_lf=final_lf)
    ):
        _fail(f"{label} is not canonical JSON")
    return value


def _contract(role: str) -> RoleContract:
    if type(role) is not str or role not in CONTRACTS:
        _fail("EVM static acquisition role is unsupported")
    return CONTRACTS[role]


def load_reviewed_policy(
    role: str, policy_raw: bytes, *, managed_evm_policy_raw: bytes | None = None,
) -> dict[str, Any]:
    """Validate exact reviewed policy bytes without conferring authority."""

    contract = _contract(role)
    if role == "medusa":
        try:
            value = medusa.load_medusa_acquisition_policy(policy_raw)
        except medusa.MedusaReleasePolicyError as exc:
            raise NativeEVMStaticAcquisitionError(str(exc)) from None
        if len(policy_raw) != contract.policy_size:
            _fail("medusa policy exact bytes differ")
        return value
    value = _decode_exact(
        policy_raw, digest=SOLC_POLICY_SHA256, size=SOLC_POLICY_SIZE,
        label="solc-amd64 policy", final_lf=True,
    )
    if frozenset(value) != {
        "artifact", "materialization", "reviewed_source", "schema"
    } or value.get("schema") != "plamen.solc-amd64-acquisition-policy.v1":
        _fail("solc-amd64 policy field set or schema differs")
    artifact = value.get("artifact")
    materialization = value.get("materialization")
    reviewed = value.get("reviewed_source")
    if (
        type(artifact) is not dict or artifact != _solc_artifact()
        or materialization != {
            "acquisition_scope": "SETUP_ONLY",
            "ambient_solc_select": "DENY", "audit_network": "DENY",
            "identity_mode": "STATIC_PAYLOAD",
            "next_required_authority": NEXT_REQUIRED_AUTHORITY,
            "rosetta_required": True,
        }
        or reviewed != {
            "path": MANAGED_EVM_POLICY_PATH,
            "schema": "plamen.managed-evm-python-toolchain-policy.v1",
            "sha256": MANAGED_EVM_POLICY_SHA256,
            "size": MANAGED_EVM_POLICY_SIZE,
            "target_id": "linux-x86_64",
        }
    ):
        _fail("solc-amd64 reviewed policy semantics differ")
    if managed_evm_policy_raw is None:
        _fail("managed-EVM parent policy bytes are required")
    parent = _decode_exact(
        managed_evm_policy_raw, digest=MANAGED_EVM_POLICY_SHA256,
        size=MANAGED_EVM_POLICY_SIZE, label="managed-EVM parent policy",
        final_lf=True, canonical=False,
    )
    targets = parent.get("targets")
    matches = [row for row in targets if type(row) is dict and row.get("id") == "linux-x86_64"] if type(targets) is list else []
    if (
        parent.get("schema") != reviewed["schema"] or len(matches) != 1
        or matches[0].get("machine") != "x86_64"
        or matches[0].get("sys_platform") != "linux"
        or matches[0].get("status") != "SUPPORTED"
        or matches[0].get("compiler") != _managed_solc_compiler()
    ):
        _fail("solc-amd64 parent policy projection differs")
    return value


def _managed_solc_compiler() -> dict[str, Any]:
    return {
        "architectures": ["x86_64"], "binary_format": "ELF",
        "build": "commit.8a97fa7a",
        "filename": "solc-linux-amd64-v0.8.26+commit.8a97fa7a",
        "install_relative_path": "solc/0.8.26/solc",
        "long_version": "0.8.26+commit.8a97fa7a",
        "minimum_os": "glibc-compatible manylinux2014 host", "name": "solc",
        "provider_index_sha256": "ee1a2b4811bd1225c220cd2342e2b49a58cbe18f5687f230f456c443b29497d6",
        "provider_index_url": "https://binaries.soliditylang.org/linux-amd64/list.json",
        "sha256": SOLC_AMD64.payload_sha256, "size": SOLC_AMD64.payload_size,
        "source_url": SOLC_AMD64.source_reference, "version": "0.8.26",
    }


def _solc_artifact() -> dict[str, Any]:
    return {
        "artifact_id": SOLC_AMD64.artifact_id,
        "binary": {
            "build": "commit.8a97fa7a",
            "filename": "solc-linux-amd64-v0.8.26+commit.8a97fa7a",
            "keccak256": "9d138fc8bb5c20b4aaaa3a868d16eb897584ce8536a5c3a466d718e47ccbafb7",
            "long_version": SOLC_AMD64.version,
            "sha256": SOLC_AMD64.payload_sha256,
            "size": SOLC_AMD64.payload_size,
            "url": SOLC_AMD64.source_reference, "version": "0.8.26",
        },
        "install": {
            "media_type": "application/vnd.plamen.executable", "mode": "0555",
            "path": SOLC_AMD64.install_path, "role": SOLC_AMD64.role,
        },
        "platform": SOLC_AMD64.platform,
        "provider_index": {
            "release_key": "0.8.26",
            "selected_path": "solc-linux-amd64-v0.8.26+commit.8a97fa7a",
            "sha256": "ee1a2b4811bd1225c220cd2342e2b49a58cbe18f5687f230f456c443b29497d6",
            "size": 47_730,
            "url": "https://binaries.soliditylang.org/linux-amd64/list.json",
        },
    }


def _source_manifest(contract: RoleContract) -> bytes:
    return _canonical({
        "artifact_id": contract.artifact_id,
        "authentication_scope": AUTHENTICATION_SCOPE,
        "media_type": "application/vnd.plamen.executable",
        "payload_sha256": contract.payload_sha256,
        "payload_size": contract.payload_size,
        "platform": contract.platform,
        "required_paths": [contract.install_path], "role": contract.role,
        "schema_version": SOURCE_MANIFEST_SCHEMA,
        "source_reference": contract.source_reference,
        "version": contract.version,
    }, final_lf=True)


def _semantic_receipt(contract: RoleContract) -> bytes:
    manifest = _source_manifest(contract)
    common: dict[str, Any] = {
        "artifact_id": contract.artifact_id,
        "generation": {"renderer": RENDERER_PATH, "schema": RENDERER_SCHEMA},
        "payload": {"sha256": contract.payload_sha256, "size": contract.payload_size},
        "platform": contract.platform, "policy_sha256": contract.policy_sha256,
        "role": contract.role, "schema": contract.receipt_schema,
        "source_manifest": {
            "sha256": hashlib.sha256(manifest).hexdigest(), "size": len(manifest),
        },
        "version": contract.version,
    }
    if contract.role == "medusa":
        common["authentication"] = {
            "archive": {"sha256": medusa.ARCHIVE_SHA256, "size": medusa.ARCHIVE_SIZE},
            "certificate_identity": medusa.CERTIFICATE_IDENTITY,
            "certificate_oidc_issuer": medusa.CERTIFICATE_OIDC_ISSUER,
            "sigstore_bundle": {
                "sha256": medusa.SIGSTORE_BUNDLE_SHA256,
                "size": medusa.SIGSTORE_BUNDLE_SIZE,
            },
            "source_commit": medusa.SOURCE_COMMIT,
        }
        common["materialization"] = {
            "archive_format": "tar.gz", "archive_member": "medusa",
            "destination": contract.install_path, "mode": "0555",
            "projection": "EXACT_SOLE_REGULAR_MEMBER_V1",
        }
    else:
        artifact = _solc_artifact()
        common["authentication"] = {
            "provider_index": {
                "sha256": artifact["provider_index"]["sha256"],
                "size": artifact["provider_index"]["size"],
            },
            "reviewed_parent_policy": {
                "sha256": MANAGED_EVM_POLICY_SHA256, "size": MANAGED_EVM_POLICY_SIZE,
            },
        }
        common["selection"] = {
            "build": "commit.8a97fa7a",
            "keccak256": artifact["binary"]["keccak256"],
            "long_version": contract.version,
            "path": artifact["provider_index"]["selected_path"],
            "release_key": artifact["provider_index"]["release_key"],
            "sha256": contract.payload_sha256, "version": "0.8.26",
        }
        common["materialization"] = {
            "destination": contract.install_path, "mode": "0555",
            "projection": "EXACT_PROVIDER_SELECTED_EXECUTABLE_V1",
        }
    return _canonical(common, final_lf=False)


def render_assets(
    role: str, policy_raw: bytes, *, managed_evm_policy_raw: bytes | None = None,
) -> tuple[bytes, bytes]:
    """Return ``(semantic receipt prefix, source manifest)`` exact bytes."""

    contract = _contract(role)
    load_reviewed_policy(
        role, policy_raw, managed_evm_policy_raw=managed_evm_policy_raw,
    )
    receipt, manifest = _semantic_receipt(contract), _source_manifest(contract)
    _require_render_freeze(contract, receipt, manifest)
    return receipt, manifest


def _require_render_freeze(
    contract: RoleContract, receipt: bytes, manifest: bytes,
) -> None:
    if (
        len(receipt) != contract.receipt_size
        or hashlib.sha256(receipt).hexdigest() != contract.receipt_sha256
        or len(manifest) != contract.source_manifest_size
        or hashlib.sha256(manifest).hexdigest()
        != contract.source_manifest_sha256
    ):
        _fail(f"{contract.role} renderer output differs from the reviewed freeze")


def validate_semantic_receipt(role: str, raw: bytes) -> dict[str, Any]:
    contract = _contract(role)
    expected = _semantic_receipt(contract)
    return _decode_exact(
        raw, digest=contract.receipt_sha256, size=contract.receipt_size,
        label=f"{role} semantic receipt", final_lf=False,
    )


def validate_source_manifest(role: str, raw: bytes) -> dict[str, Any]:
    contract = _contract(role)
    expected = _source_manifest(contract)
    return _decode_exact(
        raw, digest=contract.source_manifest_sha256,
        size=contract.source_manifest_size,
        label=f"{role} source manifest", final_lf=True,
    )


def native_operation4_evm_policy_input(role: str) -> dict[str, Any]:
    """Project an exact compile-time row; never issue production authority."""

    contract = _contract(role)
    receipt, manifest = _semantic_receipt(contract), _source_manifest(contract)
    _require_render_freeze(contract, receipt, manifest)
    return {
        "identity_mode": STATIC_PAYLOAD_IDENTITY_MODE,
        "payload_sha256": contract.payload_sha256,
        "payload_size": contract.payload_size,
        "policy_sha256": contract.policy_sha256,
        "producer_fd_size": contract.receipt_size + PRODUCER_FOOTER_SIZE,
        "receipt_schema": contract.receipt_schema,
        "receipt_validator": contract.receipt_validator,
        "role": contract.role, "role_ordinal": contract.ordinal,
        "semantic_receipt_sha256": contract.receipt_sha256,
        "semantic_receipt_size": contract.receipt_size,
        "source_manifest_sha256": contract.source_manifest_sha256,
        "source_manifest_size": contract.source_manifest_size,
        "version": contract.version,
    }


def native_coordinator_evm_acquisition_input(role: str) -> dict[str, Any]:
    """Describe the retained native producer ABI without exposing/issuing FDs."""

    contract = _contract(role)
    inputs = (
        (
            {"kind": "medusa_release_archive", "sha256": medusa.ARCHIVE_SHA256,
             "size": medusa.ARCHIVE_SIZE},
            {"kind": "medusa_sigstore_bundle", "sha256": medusa.SIGSTORE_BUNDLE_SHA256,
             "size": medusa.SIGSTORE_BUNDLE_SIZE},
        ) if role == "medusa" else (
            {"kind": "solc_provider_index", "sha256": _solc_artifact()["provider_index"]["sha256"],
             "size": _solc_artifact()["provider_index"]["size"]},
            {"kind": "solc_selected_binary", "sha256": contract.payload_sha256,
             "size": contract.payload_size},
        )
    )
    return {
        "next_required_authority": NEXT_REQUIRED_AUTHORITY,
        "ordered_retained_inputs": inputs,
        "policy_row": native_operation4_evm_policy_input(role),
        "producer_output": {
            "footer_size": PRODUCER_FOOTER_SIZE,
            "semantic_prefix_path": contract.receipt_path,
            "source_manifest_path": contract.source_manifest_path,
            "wire": "CANONICAL_SEMANTIC_PREFIX_NO_LF_THEN_NATIVE_FOOTER_V1",
        },
        "production_authority": False,
        "required_native_replay": (
            "SIGSTORE_BUNDLE_AND_SOLE_ARCHIVE_MEMBER_V1" if role == "medusa"
            else "SOLC_PROVIDER_INDEX_SELECTION_AND_BINARY_V1"
        ),
        "role": role,
    }


def _main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("kind", choices=("receipt", "source-manifest"))
    parser.add_argument("role", choices=tuple(CONTRACTS))
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args(argv)
    policy = (args.root / _contract(args.role).policy_path).read_bytes()
    parent = None
    if args.role == "solc_amd64":
        parent = (args.root / MANAGED_EVM_POLICY_PATH).read_bytes()
    receipt, manifest = render_assets(
        args.role, policy, managed_evm_policy_raw=parent,
    )
    sys.stdout.buffer.write(receipt if args.kind == "receipt" else manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))


__all__ = [
    "CONTRACTS", "MEDUSA", "SOLC_AMD64", "NativeEVMStaticAcquisitionError",
    "RoleContract", "load_reviewed_policy", "native_coordinator_evm_acquisition_input",
    "native_operation4_evm_policy_input", "render_assets",
    "validate_semantic_receipt", "validate_source_manifest",
]
