"""P3 — EVM input preparation and FOUNDRY_PROFILE resolution.

Unreviewed Forge/Soldeer materialization stays unavailable before native
authority.  A legacy direct JavaScript lane may execute only the unique exact
manifest-consistent lock selected by the shared lock authority.
"""
from __future__ import annotations

import importlib
import base64
import hashlib
import os
import sys
import types
from pathlib import Path
from unittest import mock


def _rp():
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    return importlib.import_module("recon_prepass")


def _mk(p: Path, body: str = "x"):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding="utf-8")


def _reviewed_yarn_inputs(root: Path) -> None:
    _mk(
        root / "package.json",
        '{"dependencies":{"dependency":"^1.0.0"},"name":"fixture","version":"1.0.0"}\n',
    )
    integrity = "sha512-" + base64.b64encode(
        hashlib.sha512(b"dependency").digest()
    ).decode("ascii")
    _mk(
        root / "yarn.lock",
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
        "# yarn lockfile v1\n\n"
        '"dependency@^1.0.0":\n'
        '  version "1.2.3"\n'
        '  resolved "https://registry.yarnpkg.com/dependency/-/dependency-1.2.3.tgz"\n'
        f"  integrity {integrity}\n",
    )


# ── FOUNDRY_PROFILE resolution ───────────────────────────────────────────────

def test_profile_honors_env(tmp_path, monkeypatch):
    rp = _rp()
    _mk(tmp_path / "foundry.toml", "[profile.default]\n[profile.ci]\n")
    monkeypatch.setenv("FOUNDRY_PROFILE", "ci")
    assert rp._resolve_foundry_profile_for_recon(tmp_path) == "ci"


def test_profile_default_present_returns_none(tmp_path, monkeypatch):
    rp = _rp()
    monkeypatch.delenv("FOUNDRY_PROFILE", raising=False)
    _mk(tmp_path / "foundry.toml", "[profile.default]\nsrc='src'\n[profile.ci]\n")
    assert rp._resolve_foundry_profile_for_recon(tmp_path) is None


def test_profile_single_nondefault_autoselected(tmp_path, monkeypatch):
    rp = _rp()
    monkeypatch.delenv("FOUNDRY_PROFILE", raising=False)
    _mk(tmp_path / "foundry.toml", "[profile.contracts]\nsrc='src'\nvia-ir=true\n")
    assert rp._resolve_foundry_profile_for_recon(tmp_path) == "contracts"


def test_profile_multiple_nondefault_not_guessed(tmp_path, monkeypatch):
    rp = _rp()
    monkeypatch.delenv("FOUNDRY_PROFILE", raising=False)
    _mk(tmp_path / "foundry.toml", "[profile.a]\n[profile.b]\n")
    assert rp._resolve_foundry_profile_for_recon(tmp_path) is None


# ── dependency preparation ───────────────────────────────────────────────────

def test_soldeer_is_not_launched_without_presnapshot_authority(tmp_path, monkeypatch):
    rp = _rp()
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[dependencies]\n\"@oz\" = \"5.0.0\"\n")
    _mk(root / "src" / "A.sol", "contract A {}\n")  # dependencies/ absent
    monkeypatch.setattr(rp.shutil, "which", lambda n: "/usr/bin/" + n)
    monkeypatch.setattr(
        rp, "_run_cmd",
        lambda *a, **k: (_ for _ in ()).throw(AssertionError("unexpected launch")),
    )
    note = rp._prepare_evm_build(root)
    assert "FORGE_PRE_SNAPSHOT_AUTHORITY_UNAVAILABLE" in note


def test_npm_ci_when_lockfile_and_node_modules_absent(tmp_path, monkeypatch):
    rp = _rp()
    # Isolate from the fail-closed supply-chain gate: with a lockfile present but
    # no offline-scanner binary on PATH (a clean CI runner), the gate aborts by
    # design. This test targets npm-vs-pnpm selection, not the gate.
    monkeypatch.setattr(rp, "gate_supply_chain", lambda root: None)
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[profile.default]\n")
    _mk(root / "package.json", '{"name":"fixture","version":"1.0.0"}\n')
    _mk(
        root / "package-lock.json",
        '{"lockfileVersion":3,"name":"fixture","packages":{"":'
        '{"name":"fixture","version":"1.0.0"}},"requires":true,'
        '"version":"1.0.0"}\n',
    )
    _mk(root / "src" / "A.sol", "contract A {}\n")
    cmds = []
    monkeypatch.setattr(rp.shutil, "which", lambda n: "/usr/bin/" + n if n in ("npm",) else None)
    monkeypatch.setattr(rp, "_run_cmd", lambda cmd, cwd, t: (cmds.append(cmd) or 0))
    note = rp._prepare_evm_build(root)
    assert ["npm", "ci"] in cmds
    assert "npm ci ok" in note


def test_pnpm_lock_is_rejected_until_its_parser_is_reviewed(tmp_path, monkeypatch):
    rp = _rp()
    monkeypatch.setattr(rp, "gate_supply_chain", lambda _root: None)
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[profile.default]\n")
    _mk(root / "package.json", "{}")
    _mk(root / "pnpm-lock.yaml", "")
    _mk(root / "src" / "A.sol", "contract A {}\n")
    cmds = []
    monkeypatch.setattr(rp.shutil, "which", lambda n: "/usr/bin/" + n)
    monkeypatch.setattr(rp, "_run_cmd", lambda cmd, cwd, t: (cmds.append(cmd) or 0))
    note = rp._prepare_evm_build(root)
    assert not cmds
    assert "UNSUPPORTED_LOCK_FAMILY_PRESENT" in note


def test_no_install_when_node_modules_present(tmp_path, monkeypatch):
    rp = _rp()
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[profile.default]\n")
    _mk(root / "package.json", "{}")
    _mk(root / "node_modules" / "dep" / "index.js", "//")  # already installed
    _mk(root / "src" / "A.sol", "contract A {}\n")
    cmds = []
    monkeypatch.setattr(rp.shutil, "which", lambda n: "/usr/bin/" + n)
    monkeypatch.setattr(rp, "_run_cmd", lambda cmd, cwd, t: (cmds.append(cmd) or 0))
    rp._prepare_evm_build(root)
    assert not any(c[0] in ("npm", "yarn", "pnpm") for c in cmds)


def test_prepare_never_raises(tmp_path):
    rp = _rp()
    # non-existent root must not raise
    assert isinstance(rp._prepare_evm_build(tmp_path / "nope"), str)


def test_snapshot_preparation_materializes_declared_deps_before_binding(
    tmp_path, monkeypatch,
):
    rp = _rp()
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[profile.default]\nsrc='src'\n")
    _mk(root / "src" / "Vault.sol", "pragma solidity 0.8.21; contract Vault {}\n")
    calls = []
    monkeypatch.setattr(
        rp,
        "_prepare_evm_build",
        lambda build_root: (calls.append(Path(build_root)) or "deps ready"),
    )

    receipt = rp.prepare_snapshot_bound_inputs(
        {"project_root": str(root), "pipeline": "sc", "language": "evm"}
    )

    assert calls == [root.resolve()]
    assert receipt["status"] == "PREPARED"
    assert "deps ready" in receipt["reason"]


def test_native_snapshot_preparation_routes_declared_js_through_projection(
    tmp_path, monkeypatch,
):
    rp = _rp()
    root = tmp_path / "proj"
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    _mk(root / "package.json", '{"dependencies":{"dependency":"^1.0.0"}}\n')
    _mk(root / "yarn.lock", "# yarn lockfile v1\n")
    _mk(root / "contracts" / "Vault.sol", "contract Vault {}\n")
    native = object()
    calls = []

    def project(config, build_root, *, native_runtime_authority):
        calls.append((config, build_root, native_runtime_authority))
        return "native projection ready"

    monkeypatch.setattr(rp, "_prepare_native_js_evm_projection", project)
    monkeypatch.setattr(
        rp, "_prepare_evm_build", lambda *_args: (_ for _ in ()).throw(
            AssertionError("ambient EVM preparation must not run")
        )
    )
    config = {
        "_run_id": "run-1",
        "project_root": str(root),
        "scratchpad": str(scratch),
        "pipeline": "sc",
        "language": "evm",
    }
    receipt = rp.prepare_snapshot_bound_inputs(
        config, native_runtime_authority=native
    )

    assert calls == [(config, root.resolve(), native)]
    assert receipt["status"] == "PREPARED"
    assert receipt["reason"] == "native projection ready"


def test_native_snapshot_preparation_rejects_declared_non_js_build(tmp_path):
    import pytest

    rp = _rp()
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[profile.default]\n")
    _mk(root / "src" / "Vault.sol", "contract Vault {}\n")

    with pytest.raises(
        rp.BuildContextResolutionError,
        match="requires a declared JavaScript package",
    ):
        rp.prepare_snapshot_bound_inputs(
            {
                "_run_id": "run-1",
                "project_root": str(root),
                "scratchpad": str(tmp_path / "scratch"),
                "pipeline": "sc",
                "language": "evm",
            },
            native_runtime_authority=object(),
        )


def test_native_projection_binds_opaque_authority_and_staging_paths(
    tmp_path, monkeypatch,
):
    rp = _rp()
    import evm_analysis_workspace_authority as workspace_authority
    import js_dependency_materializer_runtime as runtime

    project = tmp_path / "project"
    scratch = tmp_path / "scratch"
    scratch.mkdir(mode=0o700)
    _reviewed_yarn_inputs(project)
    _mk(project / "contracts" / "Vault.sol", "contract Vault {}\n")
    run_id = "run-123"
    private = (
        scratch / ".evm-analysis-projection-staging"
        / f"js-materialization-{run_id}"
    )
    projection = private / "evm-analysis-projection"
    receipt = projection / "state" / "projection-receipt.json"
    lineage = projection / "state" / "materialization-lineage.json"
    workspace = projection / "scratch" / "analysis-workspace"
    native = object()
    projection_authority = object()
    observed = {}

    def execute(source, private_inputs, **kwargs):
        observed.update(source=source, workspace=private_inputs, kwargs=kwargs)
        return types.SimpleNamespace(
            workspace_binding={"workspace_path": str(workspace)},
            projection_receipt_path=str(receipt),
            materialization_lineage_path=str(lineage),
            native_projection_authority=projection_authority,
        )

    monkeypatch.setattr(
        rp._audit_snapshot_authority,
        "_source_component",
        lambda _config: {"digest": "3" * 64},
    )
    monkeypatch.setattr(
        runtime, "execute_native_guest_js_and_evm_analysis_projection", execute
    )
    config = {
        "_run_id": run_id,
        "project_root": str(project),
        "scratchpad": str(scratch),
        "pipeline": "sc",
        "language": "evm",
    }

    note = rp._prepare_native_js_evm_projection(
        config, project.resolve(), native_runtime_authority=native
    )

    assert "authenticated native Yarn" in note
    assert observed["source"].source_snapshot_sha256 == "3" * 64
    assert dict(observed["source"].lockfiles).keys() == {"yarn.lock"}
    assert observed["workspace"].private_root == str(private)
    assert observed["kwargs"]["native_runtime_authority"] is native
    assert observed["kwargs"]["original_source_scope_sha256"] == "3" * 64
    assert config["_resolved_build_root"] == str(workspace)
    assert config[
        workspace_authority.ANALYSIS_PROJECTION_NATIVE_AUTHORITY_CONFIG
    ] is projection_authority
    assert config[
        workspace_authority.ANALYSIS_PROJECTION_STAGING_RECEIPT_CONFIG
    ] == str(receipt)
    assert config[
        workspace_authority.MATERIALIZATION_LINEAGE_STAGING_CONFIG
    ] == str(lineage)


def test_native_projection_reexecutes_into_fresh_root_after_precheckpoint_crash(
    tmp_path, monkeypatch,
):
    rp = _rp()
    import js_dependency_materializer_runtime as runtime

    project = tmp_path / "project"
    scratch = tmp_path / "scratch"
    scratch.mkdir(mode=0o700)
    _reviewed_yarn_inputs(project)
    run_id = "run-123"
    projection = (
        scratch / ".evm-analysis-projection-staging"
        / f"js-materialization-{run_id}" / "evm-analysis-projection"
    )
    _mk(projection / "state" / "projection-receipt.json", "{}")
    _mk(projection / "state" / "materialization-lineage.json", "{}")
    (projection / "scratch" / "analysis-workspace").mkdir(parents=True)
    (scratch / ".evm-analysis-projection-staging").chmod(0o700)
    observed = {}

    def execute(_source, private_inputs, **_kwargs):
        fresh = Path(private_inputs.private_root) / "evm-analysis-projection"
        observed["private_root"] = private_inputs.private_root
        return types.SimpleNamespace(
            workspace_binding={
                "workspace_path": str(
                    fresh / "scratch" / "analysis-workspace"
                )
            },
            projection_receipt_path=str(fresh / "state" / "projection-receipt.json"),
            materialization_lineage_path=str(
                fresh / "state" / "materialization-lineage.json"
            ),
            native_projection_authority=object(),
        )

    monkeypatch.setattr(
        rp._audit_snapshot_authority,
        "_source_component",
        lambda _config: {"digest": "3" * 64},
    )
    monkeypatch.setattr(
        runtime, "execute_native_guest_js_and_evm_analysis_projection", execute
    )
    config = {
        "_run_id": run_id,
        "project_root": str(project),
        "scratchpad": str(scratch),
        "pipeline": "sc",
        "language": "evm",
    }

    note = rp._prepare_native_js_evm_projection(
        config, project.resolve(), native_runtime_authority=object()
    )

    assert note.startswith("authenticated native Yarn")
    assert observed["private_root"].endswith("-attempt-0002")
    assert config["_resolved_build_root"].endswith("analysis-workspace")


def test_snapshot_preparation_does_not_swallow_supply_chain_abort(
    tmp_path, monkeypatch,
):
    rp = _rp()
    root = tmp_path / "proj"
    _mk(root / "foundry.toml", "[profile.default]\n")
    _mk(root / "src" / "Vault.sol", "pragma solidity 0.8.21; contract Vault {}\n")
    monkeypatch.setattr(
        rp,
        "_prepare_evm_build",
        lambda _root: (_ for _ in ()).throw(rp.SupplyChainAbortError("blocked")),
    )

    import pytest
    with pytest.raises(rp.SupplyChainAbortError, match="blocked"):
        rp.prepare_snapshot_bound_inputs(
            {"project_root": str(root), "pipeline": "sc", "language": "evm"}
        )


def test_snapshot_build_root_resolution_is_read_only_for_parent_scope(tmp_path):
    rp = _rp()
    root = tmp_path / "repo"
    scope = root / "contracts"
    _mk(root / "foundry.toml", "[profile.default]\n")
    _mk(scope / "Vault.sol", "pragma solidity 0.8.21; contract Vault {}\n")
    config = {"project_root": str(scope), "pipeline": "sc", "language": "evm"}
    before = sorted(path.relative_to(root) for path in root.rglob("*"))

    resolved = rp.resolve_snapshot_build_root(config)

    assert resolved == root.resolve()
    assert config["_resolved_build_root"] == str(root.resolve())
    assert sorted(path.relative_to(root) for path in root.rglob("*")) == before


def test_projection_build_root_does_not_redefine_original_source_scope(tmp_path):
    rp = _rp()
    root = tmp_path / "project"
    projection = tmp_path / "projection"
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    _mk(root / "foundry.toml", "[profile.default]\nlibs=['lib']\n")
    _mk(root / "contracts" / "Vault.sol", "contract Vault {}\n")
    _mk(root / "lib" / "dep" / "Dep.sol", "library Dep {}\n")
    _mk(projection / "foundry.toml", "[profile.default]\nlibs=['lib']\n")
    _mk(projection / "contracts" / "Vault.sol", "contract Vault { uint x; }\n")
    _mk(projection / "lib" / "dep" / "Dep.sol", "library Dep { uint x; }\n")
    config = {
        "project_root": str(root),
        "scratchpad": str(scratch),
        "pipeline": "sc",
        "language": "evm",
    }
    rp.resolve_snapshot_build_root(config)
    before = rp._audit_snapshot_authority._source_component(config)

    config["_resolved_build_root"] = str(projection)
    after = rp._audit_snapshot_authority._source_component(config)

    assert after["digest"] == before["digest"]


def test_snapshot_build_root_resolution_covers_l1_go_parent(tmp_path):
    rp = _rp()
    root = tmp_path / "node"
    scope = root / "consensus"
    _mk(root / "go.mod", "module example.invalid/node\n")
    _mk(scope / "engine.go", "package consensus\n")
    config = {"project_root": str(scope), "pipeline": "l1", "language": "go"}

    assert rp.resolve_snapshot_build_root(config) == root.resolve()
    assert config["_resolved_build_root"] == str(root.resolve())


if __name__ == "__main__":
    import pytest
    raise SystemExit(pytest.main([__file__, "-q"]))
