"""Adversarial tests for the governed JavaScript dependency runtime."""

from __future__ import annotations

from dataclasses import replace
import base64
import hashlib
import inspect
import json
import os
from pathlib import Path
import shutil
import stat
import sys
import types

import pytest

import js_dependency_materializer_authority as AUTH
import js_dependency_materializer_runtime as RUNTIME
import js_lock_authority as LOCK


def _sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _canonical(value: object) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("ascii")


def _integrity(value: str) -> str:
    return "sha512-" + base64.b64encode(hashlib.sha512(value.encode()).digest()).decode()


def _package() -> bytes:
    return b'{"dependencies":{"dependency":"^1.0.0"},"devDependencies":{"dev":"~2.0.0"},"name":"fixture","version":"1.0.0"}\n'


def _yarn() -> bytes:
    return (
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
        "# yarn lockfile v1\n\n"
        '"dependency@^1.0.0":\n'
        '  version "1.2.3"\n'
        '  resolved "https://registry.yarnpkg.com/dependency/-/dependency-1.2.3.tgz"\n'
        f"  integrity {_integrity('dependency')}\n\n"
        '"dev@~2.0.0":\n'
        '  version "2.0.1"\n'
        '  resolved "https://registry.npmjs.org/dev/-/dev-2.0.1.tgz"\n'
        f"  integrity {_integrity('dev')}\n"
    ).encode()


def _stale_npm() -> bytes:
    return (
        json.dumps(
            {
                "name": "fixture",
                "version": "1.0.0",
                "lockfileVersion": 3,
                "packages": {
                    "": {
                        "name": "fixture",
                        "version": "1.0.0",
                        "dependencies": {"dependency": "^9.0.0"},
                        "devDependencies": {},
                    }
                },
            },
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode()


def _phase(
    private: Path,
    source: Path,
    node: Path,
    yarn: Path,
    *,
    name: str,
    offline: bool,
) -> AUTH.DependencyPhaseContract:
    root = private / name
    argv = (
        str(node),
        str(yarn),
        "install",
        "--no-default-rc",
        "--ignore-path",
        "--frozen-lockfile",
        "--ignore-scripts",
        "--production=false",
        "--no-bin-links",
        "--non-interactive",
        "--modules-folder",
        str(root / "modules"),
        "--cache-folder",
        str(root / "cache"),
        "--mutex",
        f"file:{root / 'temp' / 'yarn-install.mutex'}",
    ) + (("--offline",) if offline else ("--registry", "https://registry.yarnpkg.com"))
    return AUTH.DependencyPhaseContract(
        phase="offline" if offline else "online",
        cwd=str(source),
        argv=argv,
        environment=tuple(
            sorted(
                {
                    "HOME": str(root / "home"),
                    "USERPROFILE": str(root / "home"),
                    "XDG_CONFIG_HOME": str(root / "home" / ".config"),
                    "XDG_CACHE_HOME": str(root / "cache"),
                    "PATH": str(node.parent),
                    "NODE_ENV": "development",
                    "YARN_CACHE_FOLDER": str(root / "cache"),
                    "YARN_GLOBAL_FOLDER": str(root / "cache" / "global"),
                    "YARN_IGNORE_PATH": "1",
                    "TMPDIR": str(root / "temp"),
                    "TMP": str(root / "temp"),
                    "TEMP": str(root / "temp"),
                    "PLAMEN_JS_NETWORK_MODE": (
                        "NO_NETWORK"
                        if offline
                        else "VERIFIED_EXACT_LOCK_ORIGIN_ALLOWLIST"
                    ),
                    **(
                        {}
                        if offline
                        else {
                            "PLAMEN_JS_EGRESS_TARGET_ID": "yarn-classic-registry",
                            "PLAMEN_JS_EGRESS_TARGET_AUTHORITY_SHA256": _sha(
                                b"egress-target"
                            ),
                        }
                    ),
                }.items()
            )
        ),
        network_mode=(
            "NO_NETWORK"
            if offline
            else "VERIFIED_EXACT_LOCK_ORIGIN_ALLOWLIST"
        ),
        egress_target_id="" if offline else "yarn-classic-registry",
        private_root=str(root),
        home_root=str(root / "home"),
        modules_root=str(root / "modules"),
        cache_root=str(root / "cache"),
        temp_root=str(root / "temp"),
        phase_timeout_seconds=30,
        max_dependency_entries=100,
        max_dependency_expanded_bytes=1024 * 1024,
        max_cache_expanded_bytes=1024 * 1024,
        required_preconditions=(
            (
                "SAME_SOURCE_SNAPSHOT_RETAINED_READ_ONLY",
                "OFFLINE_PRIVATE_ROOT_PROVEN_EMPTY",
                "ONLINE_TERMINAL_RECEIPT_VERIFIED",
                "ONLINE_CACHE_SNAPSHOT_RETAINED_READ_ONLY",
                "OFFLINE_CACHE_SEED_COPIED_BYTE_EXACTLY",
                "NO_NETWORK_ACTIVE_BEFORE_PROCESS_START",
            )
            if offline
            else (
                "SOURCE_SNAPSHOT_RETAINED_READ_ONLY",
                "ONLINE_PRIVATE_ROOT_PROVEN_EMPTY",
                "TOOLCHAIN_ARCHIVES_RETAINED_AND_DIGEST_VERIFIED",
                "TOOLCHAIN_EXTRACTION_RECEIPT_VERIFIED",
                "VERIFIED_EXACT_LOCK_ORIGIN_ALLOWLIST_ACTIVE_BEFORE_PROCESS_START",
            )
        ),
    )


def _contract(tmp_path: Path) -> AUTH.JSDependencyMaterializationContract:
    source = tmp_path / "source"
    source.mkdir(mode=0o700)
    package = _package()
    yarn_lock = _yarn()
    npm_lock = _stale_npm()
    (source / "package.json").write_bytes(package)
    (source / "yarn.lock").write_bytes(yarn_lock)
    (source / "package-lock.json").write_bytes(npm_lock)
    selection = LOCK.select_js_lock_authority(
        package, {"package-lock.json": npm_lock, "yarn.lock": yarn_lock}
    )
    assert selection.family == "yarn"
    assert {row.filename: row.error_codes for row in selection.candidates}[
        "package-lock.json"
    ] == (
        "NPM_ROOT_DEPENDENCIES_MISMATCH",
        "NPM_ROOT_DEVDEPENDENCIES_MISMATCH",
    )
    private = tmp_path / "private" / "materialized"
    private.parent.mkdir(mode=0o700)
    scratch = private / "scratch"
    archive_root = tmp_path / "archives"
    archive_root.mkdir(mode=0o700)
    node_archive = archive_root / "node.tar.gz"
    yarn_archive = archive_root / "yarn.tar.gz"
    node_archive.write_bytes(b"authenticated-node-archive")
    yarn_archive.write_bytes(b"authenticated-yarn-archive")
    node = scratch / "toolchain" / "node" / "node-v1" / "bin" / "node"
    yarn = scratch / "toolchain" / "yarn" / "yarn-v1" / "bin" / "yarn.js"
    binding = {
        "bootstrap_anchor_sha256": _sha(b"anchor"),
        "bootstrap_install_provenance_sha256": _sha(b"install"),
        "bootstrap_signed_set_sha256": _sha(b"set"),
        "bootstrap_source_census_sha256": _sha(b"census"),
        "manifest_content_sha256": _sha(b"manifest"),
        "runtime_closure_sha256": _sha(b"closure"),
        "upstream_verification_sha256": _sha(b"upstream"),
        "node_artifact_id": "node-test",
        "node_archive_sha256": _sha(node_archive.read_bytes()),
        "node_archive_path": str(node_archive),
        "node_executable_path": str(node),
        "yarn_artifact_id": "yarn-test",
        "yarn_archive_sha256": _sha(yarn_archive.read_bytes()),
        "yarn_archive_size": yarn_archive.stat().st_size,
        "yarn_archive_path": str(yarn_archive),
        "yarn_cli_path": str(yarn),
    }
    toolchain = AUTH.ToolchainBinding(
        **binding, binding_sha256=_sha(_canonical(binding))
    )
    online = _phase(scratch, source, node, yarn, name="online", offline=False)
    offline = _phase(scratch, source, node, yarn, name="offline-replay", offline=True)
    execution_binding = {
        "target_os": "linux",
        "target_arch": "x86_64",
        "controller_transaction_root": str(private),
        "controller_scratch_root": str(scratch),
        "controller_state_root": str(private / "state"),
        "guest_project_root": "/workspace/project",
        "guest_scratch_root": "/workspace/scratch",
        "guest_state_root": "/workspace/state",
        "project_access": "IMMUTABLE_READ_ONLY",
        "scratch_access": "PRIVATE_READ_WRITE",
        "state_access": "PRIVATE_READ_WRITE",
    }
    execution = AUTH.GuestExecutionBinding(
        **execution_binding,
        binding_sha256=_sha(_canonical(execution_binding)),
    )
    replay = AUTH.CleanOfflineReplayContract(
        online_cache_root=online.cache_root,
        retained_cache_snapshot_root=str(scratch / "online-cache-snapshot"),
        offline_cache_seed_root=offline.cache_root,
        cache_handoff="COPY_VERIFIED_TREE_INTO_EMPTY_OFFLINE_CACHE",
        source_snapshot_sha256=_sha(b"snapshot"),
        required_online_receipt_fields=(
            "source_snapshot_sha256", "lock_selection_sha256",
            "toolchain_binding_sha256", "modules_tree_sha256",
            "modules_entry_count", "modules_expanded_bytes",
            "cache_tree_sha256", "cache_entry_count",
            "cache_expanded_bytes", "exit_code", "network_admission_sha256",
        ),
        required_offline_receipt_fields=(
            "source_snapshot_sha256", "lock_selection_sha256",
            "toolchain_binding_sha256", "seed_cache_tree_sha256",
            "modules_tree_sha256", "modules_entry_count",
            "modules_expanded_bytes", "exit_code", "network_denial_sha256",
        ),
        required_receipt_equalities=(
            ("source_snapshot_sha256", "source_snapshot_sha256"),
            ("lock_selection_sha256", "lock_selection_sha256"),
            ("toolchain_binding_sha256", "toolchain_binding_sha256"),
            ("cache_tree_sha256", "seed_cache_tree_sha256"),
            ("modules_tree_sha256", "modules_tree_sha256"),
            ("modules_entry_count", "modules_entry_count"),
            ("modules_expanded_bytes", "modules_expanded_bytes"),
        ),
        required_terminal_conditions=(
            "ONLINE_EXIT_CODE_ZERO", "OFFLINE_EXIT_CODE_ZERO",
            "ONLINE_LIMITS_NOT_EXCEEDED", "OFFLINE_LIMITS_NOT_EXCEEDED",
            "OFFLINE_NETWORK_DENIAL_REMAINED_ACTIVE",
        ),
        tree_digest_algorithm=AUTH.TREE_DIGEST_ALGORITHM,
    )
    provisional = AUTH.JSDependencyMaterializationContract(
        schema=AUTH.SCHEMA,
        generation_id="fixture-001",
        source_access=AUTH.SOURCE_ACCESS,
        workspace_access=AUTH.WORKSPACE_ACCESS,
        source_root=str(source),
        source_snapshot_sha256=_sha(b"snapshot"),
        package_json_sha256=_sha(package),
        lock_selection=selection,
        toolchain=toolchain,
        execution=execution,
        online=online,
        offline_replay=offline,
        replay=replay,
        execution_state=AUTH.EXECUTION_STATE,
        contract_sha256="",
    )
    return replace(provisional, contract_sha256=_sha(_canonical(provisional.binding_dict())))


def _authorities() -> RUNTIME.NativeMaterializerAuthorities:
    return RUNTIME.NativeMaterializerAuthorities(
        custody_receipt_sha256=_sha(b"custody"),
        online_network_admission_sha256=_sha(b"online-network"),
        offline_network_denial_sha256=_sha(b"offline-network"),
        native_extension_sha256=_sha(b"native-extension"),
        native_deployment_receipt_sha256=_sha(b"native-deployment"),
    )


def _runtime_identity(extension_sha256: str) -> bytes:
    anchor_sha256 = _sha(b"installed-bootstrap-anchor")
    source_census_sha256 = _sha(b"installed-source-census")
    provenance_sha256 = RUNTIME.TOOLCHAIN.bootstrap_install_provenance_sha256(
        anchor_relative_path=(
            RUNTIME.TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH.as_posix()
        ),
        anchor_sha256=anchor_sha256,
        source_census_sha256=source_census_sha256,
        trust_boundary=RUNTIME.TOOLCHAIN.BOOTSTRAP_TRUST_BOUNDARY,
    )
    return _canonical(
        {
            "anchor_relative_path": (
                RUNTIME.TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH.as_posix()
            ),
            "anchor_sha256": anchor_sha256,
            "custody_receipt_sha256": _sha(b"installed-custody"),
            "install_provenance_sha256": provenance_sha256,
            "native_deployment_receipt_sha256": _sha(
                b"installed-native-deployment"
            ),
            "native_extension_sha256": extension_sha256,
            "offline_network_denial_sha256": _sha(
                b"installed-offline-denial"
            ),
            "online_network_admission_sha256": _sha(
                b"installed-online-admission"
            ),
            "schema": RUNTIME.NATIVE_RUNTIME_IDENTITY_SCHEMA,
            "source_census_sha256": source_census_sha256,
            "trust_boundary": RUNTIME.TOOLCHAIN.BOOTSTRAP_TRUST_BOUNDARY,
        }
    )


class FakeNative:
    def __init__(self, contract: AUTH.JSDependencyMaterializationContract) -> None:
        self.contract = contract
        self.calls: list[str] = []
        self.requests: list[dict[str, object]] = []
        self.fail_operation: str | None = None
        self.crash_once: str | None = None
        self.crashed = False
        self.mutate: str | None = None

    def execute(self, _capability: object, raw: bytes) -> bytes:
        request = json.loads(raw)
        self.requests.append(request)
        operation = request["operation"]
        self.calls.append(operation)
        if self.crash_once == operation and not self.crashed:
            self.crashed = True
            first_output = Path(next(iter(request["outputs"].values())))
            first_output.mkdir(parents=True, exist_ok=True)
            (first_output / "partial").write_bytes(b"partial")
            raise RuntimeError("simulated native crash")
        if self.fail_operation == operation:
            raise RuntimeError("simulated native failure")
        outputs = {name: Path(path) for name, path in request["outputs"].items()}
        if operation == "PREPARE_TOOLCHAIN":
            node = Path(self.contract.toolchain.node_executable_path)
            yarn = Path(self.contract.toolchain.yarn_cli_path)
            node.parent.mkdir(parents=True, exist_ok=True)
            yarn.parent.mkdir(parents=True, exist_ok=True)
            node.write_bytes(b"node executable")
            yarn.write_bytes(b"yarn cli")
            node.chmod(0o500)
            yarn.chmod(0o400)
        elif operation == "ONLINE_INSTALL":
            outputs["modules"].mkdir(parents=True)
            if self.mutate != "empty-modules":
                (outputs["modules"] / "dependency").mkdir()
                (outputs["modules"] / "dependency" / "index.js").write_bytes(b"module")
                (outputs["modules"] / "dependency" / "package.json").write_bytes(
                    b'{"name":"dependency","version":"1.2.3"}\n'
                )
                (outputs["modules"] / "dev").mkdir()
                (outputs["modules"] / "dev" / "package.json").write_bytes(
                    b'{"name":"dev","version":"2.0.1"}\n'
                )
                (outputs["modules"] / ".yarn-integrity").write_bytes(
                    _canonical(
                        {
                            "lockfileEntries": {
                                "dependency@^1.0.0": "https://registry.yarnpkg.com/dependency/-/dependency-1.2.3.tgz",
                                "dev@~2.0.0": "https://registry.npmjs.org/dev/-/dev-2.0.1.tgz",
                            },
                            "topLevelPatterns": [
                                "dependency@^1.0.0",
                                "dev@~2.0.0",
                            ],
                        }
                    )
                    + b"\n"
                )
                if self.mutate == "integrity":
                    (outputs["modules"] / ".yarn-integrity").write_bytes(
                        b'{"lockfileEntries":{},"topLevelPatterns":[]}\n'
                    )
                elif self.mutate == "integrity-value":
                    integrity_path = outputs["modules"] / ".yarn-integrity"
                    integrity = json.loads(integrity_path.read_bytes())
                    integrity["lockfileEntries"]["dependency@^1.0.0"] = (
                        "https://attacker.invalid/dependency-1.2.3.tgz"
                    )
                    integrity_path.write_bytes(_canonical(integrity) + b"\n")
                elif self.mutate == "package-version":
                    (outputs["modules"] / "dependency" / "package.json").write_bytes(
                        b'{"name":"dependency","version":"9.9.9"}\n'
                    )
            outputs["cache"].mkdir(parents=True)
            (outputs["cache"] / "dependency.tgz").write_bytes(b"cache-tarball")
            if self.mutate == "source":
                (Path(self.contract.source_root) / "attacker-write").write_bytes(b"x")
            elif self.mutate == "lock":
                (Path(self.contract.source_root) / "yarn.lock").write_bytes(b"changed")
            elif self.mutate == "symlink":
                os.symlink("/etc/passwd", outputs["modules"] / "alias")
            elif self.mutate == "hardlink":
                os.link(
                    outputs["modules"] / "dependency" / "index.js",
                    outputs["modules"] / "hardlink",
                )
            elif self.mutate == "toolchain":
                yarn_cli = Path(self.contract.toolchain.yarn_cli_path)
                yarn_cli.chmod(0o600)
                yarn_cli.write_bytes(b"replaced")
        elif operation == "CACHE_HANDOFF":
            source = Path(self.contract.online.cache_root)
            shutil.copytree(source, outputs["offline_cache_seed"])
            shutil.copytree(source, outputs["retained_cache_snapshot"])
            if self.mutate == "cache":
                (outputs["offline_cache_seed"] / "dependency.tgz").write_bytes(b"poison")
        elif operation == "OFFLINE_REPLAY":
            source = Path(self.contract.online.modules_root)
            shutil.copytree(source, outputs["modules"])
        if operation == "ONLINE_INSTALL" and self.mutate in {"symlink", "hardlink"}:
            # Model a compromised native implementation that signs arbitrary
            # output claims.  The independent Python tree walk must still
            # reject the unsafe object before accepting this receipt.
            observed = {
                name: {
                    "path": str(path),
                    "algorithm": RUNTIME.TREE_DIGEST_ALGORITHM,
                    "entry_count": 0,
                    "expanded_bytes": 0,
                    "sha256": _sha(b"forged-tree"),
                }
                for name, path in sorted(outputs.items())
            }
        else:
            observed = {
                name: {
                    "path": str(path),
                    **RUNTIME._scan_tree(
                        path,
                        max_entries=request["bounds"][name]["max_entries"],
                        max_bytes=request["bounds"][name]["max_bytes"],
                    ).binding_dict(),
                }
                for name, path in sorted(outputs.items())
            }
        terminal = {
            "bounds_enforced": True,
            "cleanup_complete": True,
            "contract_sha256": request["contract_sha256"],
            "dependency_expectation_sha256": request[
                "dependency_expectation_sha256"
            ],
            "duration_ms": 1,
            "exhaustive_descendant_termination": True,
            "exclusive_operation_key_lease": True,
            "exit_code": 0,
            "generation_id": request["generation_id"],
            "guest_execution_binding_sha256": request[
                "guest_execution_binding_sha256"
            ],
            "launch_object_kind": request["launch_object_kind"],
            "native_custody_receipt_sha256": request["native_custody_receipt_sha256"],
            "native_deployment_receipt_sha256": request[
                "native_deployment_receipt_sha256"
            ],
            "native_module_sha256": request["native_module_sha256"],
            "native_provider_authenticated": True,
            "network_authority_sha256": request["network_authority_sha256"],
            "network_mode": request["network_mode"],
            "network_policy_sha256": request["network_policy"][
                "policy_sha256"
            ],
            "network_violation": False,
            "observed_egress_origins": request["network_policy"][
                "allowed_origins"
            ],
            "observed_egress_sha256": RUNTIME._digest(
                request["network_policy"]["allowed_origins"]
            ),
            "operation": operation,
            "output_trees": observed,
            "population_zero": True,
            "post_spawn_dynamic_identity_sha256": _sha(b"dynamic-identity"),
            "post_spawn_dynamic_identity_kind": request["required_dynamic_identity_kind"],
            "projected_closure_manifest_sha256": request["projected_closure_manifest_sha256"],
            "request_sha256": request["request_sha256"],
            "schema": RUNTIME.NATIVE_TERMINAL_SCHEMA,
            "session_admission_sha256": request["session_admission_sha256"],
            "scratch_writes_only": True,
            "source_read_only": True,
            "stderr_bytes": 0,
            "stderr_sha256": _sha(b""),
            "stdout_bytes": 0,
            "stdout_sha256": _sha(b""),
            "timed_out": False,
            "toolchain_identity_sha256": request["toolchain_binding_sha256"],
        }
        terminal["terminal_receipt_sha256"] = _sha(_canonical(terminal))
        return _canonical(terminal) + b"\n"


def _enable_fake(monkeypatch: pytest.MonkeyPatch, fake: FakeNative) -> None:
    class FakeExecutionLease:
        pass

    class FakeTerminalReplayLease:
        pass

    pending: dict[str, bytes] = {}
    committed: set[tuple[str, str]] = set()

    def prepare(
        _authority: object,
        _session: object,
        raw: bytes,
        _source_descriptor: int,
        _scratch_descriptor: int,
        _state_descriptor: int,
        archive_root_descriptor: int,
    ) -> FakeExecutionLease:
        assert stat.S_ISDIR(os.fstat(archive_root_descriptor).st_mode)
        pending["request"] = raw
        return FakeExecutionLease()

    def execute(
        authority: object, _session: object, _lease: FakeExecutionLease
    ) -> bytes:
        terminal = fake.execute(authority, pending["request"])
        committed.add((_sha(pending["request"]), _sha(terminal)))
        return terminal

    def replay_terminal(
        _authority: object,
        _session: object,
        request: bytes,
        terminal: bytes,
        _source_descriptor: int,
        _scratch_descriptor: int,
        _state_descriptor: int,
        archive_root_descriptor: int,
    ) -> FakeTerminalReplayLease:
        assert stat.S_ISDIR(os.fstat(archive_root_descriptor).st_mode)
        if (_sha(request), _sha(terminal)) not in committed:
            raise RuntimeError("terminal was not committed by native custody")
        return FakeTerminalReplayLease()

    def runtime(
        _capability: object,
        admission: bytes,
        *,
        expected_extension_sha256: str,
    ) -> RUNTIME._NativeRuntime:
        assert expected_extension_sha256 == _authorities().native_extension_sha256
        return RUNTIME._NativeRuntime(
            authority=object(),
            session_lease=object(),
            execution_lease_type=FakeExecutionLease,
            terminal_replay_lease_type=FakeTerminalReplayLease,
            prepare_execution=prepare,
            execute=execute,
            replay_terminal=replay_terminal,
            module_sha256=expected_extension_sha256,
            session_admission_sha256=_sha(admission),
        )

    monkeypatch.setattr(
        RUNTIME,
        "_require_native_capability",
        runtime,
    )


def test_archive_root_is_canonical_content_addressed_and_retained(
    tmp_path: Path,
) -> None:
    contract = _contract(tmp_path)
    private_root = Path(contract.execution.controller_transaction_root)
    private_root.mkdir(parents=True, mode=0o700)
    retained = RUNTIME._retain_archives(contract)
    try:
        RUNTIME._stage_archive_root(retained, private_root)
        assert retained.root_descriptor >= 0
        manifest = json.loads(retained.manifest_bytes)
        assert set(manifest) == {
            "archive_census_sha256",
            "archive_count",
            "archives",
            "schema",
        }
        assert manifest["schema"] == "plamen.js-archive-root-manifest.v1"
        assert manifest["archive_census_sha256"] == _sha(
            _canonical(manifest["archives"])
        )
        assert [row["artifact_id"] for row in manifest["archives"]] == sorted(
            row["artifact_id"] for row in manifest["archives"]
        )
        assert all(
            row["filename"] == f"{row['sha256']}.archive"
            for row in manifest["archives"]
        )
        assert {entry.name for entry in os.scandir(retained.root)} == {
            "archive-manifest.json",
            *(row["filename"] for row in manifest["archives"]),
        }
        RUNTIME._verify_archive_root(retained)
    finally:
        retained.close()


@pytest.mark.parametrize("mutation", ["extra", "missing", "content"])
def test_archive_root_drift_is_rejected(tmp_path: Path, mutation: str) -> None:
    contract = _contract(tmp_path)
    private_root = Path(contract.execution.controller_transaction_root)
    private_root.mkdir(parents=True, mode=0o700)
    retained = RUNTIME._retain_archives(contract)
    try:
        RUNTIME._stage_archive_root(retained, private_root)
        root = retained.root
        assert root is not None
        archive_path = root / retained.binding["archives"][0]["filename"]
        if mutation == "extra":
            (root / "unexpected.archive").write_bytes(b"unexpected")
        elif mutation == "missing":
            archive_path.rename(root / "renamed.archive")
        else:
            archive_path.chmod(0o600)
            archive_path.write_bytes(b"substituted")
        with pytest.raises(RUNTIME.JSDependencyRuntimeError):
            RUNTIME._verify_archive_root(retained)
    finally:
        retained.close()


def test_archive_root_symlink_is_rejected(tmp_path: Path) -> None:
    contract = _contract(tmp_path)
    private_root = Path(contract.execution.controller_transaction_root)
    private_root.mkdir(parents=True, mode=0o700)
    archive_root = private_root / "archive-root"
    archive_root.symlink_to(Path(contract.toolchain.node_archive_path).parent)
    retained = RUNTIME._retain_archives(contract)
    try:
        with pytest.raises(RUNTIME.JSDependencyRuntimeError):
            RUNTIME._stage_archive_root(retained, private_root)
    finally:
        retained.close()


def _run(
    contract: AUTH.JSDependencyMaterializationContract,
) -> RUNTIME.JSDependencyMaterializationResult:
    return RUNTIME.execute_js_dependency_materialization(
        contract,
        expected_contract_sha256=contract.contract_sha256,
        authorities=_authorities(),
        native_capability=object(),
    )


def test_native_authority_hardstop_precedes_filesystem_mutation(tmp_path: Path) -> None:
    contract = _contract(tmp_path)
    private = Path(contract.execution.controller_transaction_root)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code in {
        "NATIVE_MATERIALIZER_UNAVAILABLE",
        "NATIVE_MATERIALIZER_CAPABILITY_INVALID",
    }
    assert not private.exists()


def test_authenticated_runtime_identity_maps_only_to_typed_authorities() -> None:
    extension_sha256 = _sha(b"installed-extension")
    bootstrap, authorities = RUNTIME._parse_authenticated_runtime_identity(
        _runtime_identity(extension_sha256),
        expected_native_extension_sha256=extension_sha256,
    )
    assert type(bootstrap) is RUNTIME.TOOLCHAIN.TrustedJSBootstrapAuthority
    assert type(authorities) is RUNTIME.NativeMaterializerAuthorities
    assert bootstrap.anchor_relative_path == (
        RUNTIME.TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH.as_posix()
    )
    assert bootstrap.trust_boundary == (
        RUNTIME.TOOLCHAIN.BOOTSTRAP_TRUST_BOUNDARY
    )
    assert authorities.native_extension_sha256 == extension_sha256
    assert len(set(authorities.binding_dict().values())) == 5


@pytest.mark.parametrize(
    ("mutation", "code"),
    (
        ("noncanonical", "NATIVE_RUNTIME_IDENTITY_SCHEMA_INVALID"),
        ("extra-field", "NATIVE_RUNTIME_IDENTITY_SCHEMA_INVALID"),
        ("extension", "NATIVE_RUNTIME_IDENTITY_EXTENSION_MISMATCH"),
        ("provenance", "NATIVE_RUNTIME_IDENTITY_PROVENANCE_MISMATCH"),
        ("authority-alias", "NATIVE_AUTHORITIES_ALIAS"),
    ),
)
def test_runtime_identity_forgery_fails_closed(
    mutation: str, code: str
) -> None:
    extension_sha256 = _sha(b"installed-extension")
    raw = _runtime_identity(extension_sha256)
    identity = json.loads(raw)
    if mutation == "noncanonical":
        raw += b"\n"
    elif mutation == "extra-field":
        identity["unexpected"] = "value"
        raw = _canonical(identity)
    elif mutation == "extension":
        identity["native_extension_sha256"] = _sha(b"substituted-extension")
        raw = _canonical(identity)
    elif mutation == "provenance":
        identity["install_provenance_sha256"] = _sha(b"forged-provenance")
        raw = _canonical(identity)
    else:
        identity["offline_network_denial_sha256"] = identity[
            "online_network_admission_sha256"
        ]
        raw = _canonical(identity)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        RUNTIME._parse_authenticated_runtime_identity(
            raw,
            expected_native_extension_sha256=extension_sha256,
        )
    assert raised.value.code == code


def test_installed_production_caller_has_no_authority_injection_surface() -> None:
    parameters = inspect.signature(
        RUNTIME.execute_installed_js_dependency_materialization
    ).parameters
    assert tuple(parameters) == (
        "source",
        "workspace",
        "repository_root",
        "target_os",
        "target_arch",
        "windows_system_root",
    )
    assert not {
        "authorities",
        "bootstrap_authority",
        "native_capability",
        "native_executor",
        "runtime_identity",
    }.intersection(parameters)


def test_installed_production_caller_wires_native_identity_to_exact_contract(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    extension_sha256 = _sha(b"installed-extension")
    expected_bootstrap, expected_authorities = (
        RUNTIME._parse_authenticated_runtime_identity(
            _runtime_identity(extension_sha256),
            expected_native_extension_sha256=extension_sha256,
        )
    )
    initial_authority = object()
    bridge = types.SimpleNamespace(initial_authority=initial_authority)
    source = AUTH.ImmutableJSSourceInputs(
        source_root=contract.source_root,
        source_snapshot_sha256=contract.source_snapshot_sha256,
        package_json=_package(),
        lockfiles=(("yarn.lock", _yarn()),),
    )
    workspace = AUTH.PrivateDependencyWorkspaceInputs(
        private_root=contract.execution.controller_transaction_root,
        generation_id=contract.generation_id,
        phase_timeout_seconds=30,
        max_dependency_entries=100,
        max_dependency_expanded_bytes=1024 * 1024,
        max_cache_expanded_bytes=1024 * 1024,
    )
    observed: dict[str, object] = {}

    monkeypatch.setattr(RUNTIME, "_installed_native_bridge", lambda: bridge)
    monkeypatch.setattr(
        RUNTIME,
        "_installed_runtime_authorities",
        lambda value: (
            expected_bootstrap,
            expected_authorities,
        ) if value is bridge else pytest.fail("bridge changed"),
    )

    def build(
        actual_source: object,
        actual_workspace: object,
        **kwargs: object,
    ) -> AUTH.JSDependencyMaterializationContract:
        observed["build"] = (actual_source, actual_workspace, kwargs)
        return contract

    sentinel = object()

    def execute(
        actual_contract: object, **kwargs: object
    ) -> object:
        observed["execute"] = (actual_contract, kwargs)
        return sentinel

    monkeypatch.setattr(AUTH, "build_js_dependency_materialization_contract", build)
    monkeypatch.setattr(RUNTIME, "execute_js_dependency_materialization", execute)
    result = RUNTIME.execute_installed_js_dependency_materialization(
        source,
        workspace,
        repository_root=tmp_path,
        target_os="linux",
        target_arch="x86_64",
    )
    assert result is sentinel
    assert observed["build"] == (
        source,
        workspace,
        {
            "bootstrap_authority": expected_bootstrap,
            "repository_root": tmp_path,
            "target_os": "linux",
            "target_arch": "x86_64",
            "windows_system_root": None,
        },
    )
    assert observed["execute"] == (
        contract,
        {
            "expected_contract_sha256": contract.contract_sha256,
            "authorities": expected_authorities,
            "native_capability": initial_authority,
        },
    )


def test_native_guest_bundle_caller_never_reacquires_static_initial(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import posix_backend_execution as POSIX

    contract = _contract(tmp_path)
    extension_sha256 = _sha(b"installed-extension")
    raw_identity = _runtime_identity(extension_sha256)
    expected_bootstrap, expected_authorities = (
        RUNTIME._parse_authenticated_runtime_identity(
            raw_identity,
            expected_native_extension_sha256=extension_sha256,
        )
    )
    bundle = object()
    source = AUTH.ImmutableJSSourceInputs(
        source_root=contract.source_root,
        source_snapshot_sha256=contract.source_snapshot_sha256,
        package_json=_package(),
        lockfiles=(("yarn.lock", _yarn()),),
    )
    workspace = AUTH.PrivateDependencyWorkspaceInputs(
        private_root=contract.execution.controller_transaction_root,
        generation_id=contract.generation_id,
        phase_timeout_seconds=30,
        max_dependency_entries=100,
        max_dependency_expanded_bytes=1024 * 1024,
        max_cache_expanded_bytes=1024 * 1024,
    )
    observed: dict[str, object] = {}
    monkeypatch.setattr(
        POSIX,
        "native_guest_js_materializer_runtime_identity",
        lambda value: raw_identity
        if value is bundle else pytest.fail("foreign runtime bundle"),
    )
    monkeypatch.setattr(
        RUNTIME,
        "_installed_native_bridge",
        lambda: pytest.fail("static JS INITIAL was reacquired"),
    )

    def build(actual_source: object, actual_workspace: object, **kwargs: object):
        observed["build"] = (actual_source, actual_workspace, kwargs)
        return contract

    sentinel = object()

    def execute(actual_contract: object, **kwargs: object) -> object:
        observed["execute"] = (actual_contract, kwargs)
        return sentinel

    monkeypatch.setattr(AUTH, "build_js_dependency_materialization_contract", build)
    monkeypatch.setattr(RUNTIME, "execute_js_dependency_materialization", execute)
    result = RUNTIME.execute_native_guest_js_dependency_materialization(
        source,
        workspace,
        repository_root=tmp_path,
        target_os="linux",
        target_arch="x86_64",
        native_runtime_authority=bundle,
    )
    assert result is sentinel
    assert observed["build"] == (
        source,
        workspace,
        {
            "bootstrap_authority": expected_bootstrap,
            "repository_root": tmp_path,
            "target_os": "linux",
            "target_arch": "x86_64",
            "windows_system_root": None,
        },
    )
    assert observed["execute"] == (
        contract,
        {
            "expected_contract_sha256": contract.contract_sha256,
            "authorities": expected_authorities,
            "native_runtime_authority": bundle,
        },
    )


def test_installed_production_caller_hardstops_before_contract_construction(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delitem(sys.modules, RUNTIME.NATIVE_MODULE_NAME, raising=False)
    monkeypatch.setattr(
        AUTH,
        "build_js_dependency_materialization_contract",
        lambda *_args, **_kwargs: pytest.fail("contract construction was reached"),
    )
    source = AUTH.ImmutableJSSourceInputs(
        source_root=str(tmp_path / "source"),
        source_snapshot_sha256=_sha(b"snapshot"),
        package_json=b"{}\n",
        lockfiles=(("yarn.lock", b"lock"),),
    )
    workspace = AUTH.PrivateDependencyWorkspaceInputs(
        private_root=str(tmp_path / "private"),
        generation_id="fixture-001",
        phase_timeout_seconds=30,
        max_dependency_entries=100,
        max_dependency_expanded_bytes=1024 * 1024,
        max_cache_expanded_bytes=1024 * 1024,
    )
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        RUNTIME.execute_installed_js_dependency_materialization(
            source,
            workspace,
            repository_root=tmp_path,
            target_os="linux",
            target_arch="x86_64",
        )
    assert raised.value.code == "NATIVE_MATERIALIZER_UNAVAILABLE"
    assert not (tmp_path / "private").exists()


def test_python_module_spoof_cannot_mint_native_authority(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    private = Path(contract.execution.controller_transaction_root)
    spoof = types.ModuleType(RUNTIME.NATIVE_MODULE_NAME)
    spoof.JSDependencyMaterializerAuthority = type(
        "JSDependencyMaterializerAuthority", (), {}
    )
    spoof.JSDependencyMaterializerSessionLease = type(
        "JSDependencyMaterializerSessionLease", (), {}
    )
    spoof.JSDependencyMaterializerExecutionLease = type(
        "JSDependencyMaterializerExecutionLease", (), {}
    )
    spoof.JSDependencyMaterializerTerminalReplayLease = type(
        "JSDependencyMaterializerTerminalReplayLease", (), {}
    )
    spoof.authenticate_js_dependency_materializer_capability = lambda *_: object()
    spoof.prepare_js_dependency_materializer_execution = lambda *_: object()
    spoof.execute_js_dependency_materializer = lambda *_: b"{}\n"
    spoof.replay_js_dependency_materializer_terminal = lambda *_: object()
    monkeypatch.setitem(sys.modules, RUNTIME.NATIVE_MODULE_NAME, spoof)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "NATIVE_MATERIALIZER_UNAVAILABLE"
    assert not private.exists()


@pytest.mark.parametrize("forgery", ["scripts", "modules-escape"])
def test_rehashed_forged_operation_contract_is_rejected_before_mutation(
    tmp_path: Path, forgery: str
) -> None:
    contract = _contract(tmp_path)
    phase = contract.online
    if forgery == "scripts":
        phase = replace(phase, argv=phase.argv + ("--ignore-scripts=false",))
    else:
        escaped = str(tmp_path / "escaped-modules")
        argv = list(phase.argv)
        argv[argv.index("--modules-folder") + 1] = escaped
        phase = replace(phase, argv=tuple(argv), modules_root=escaped)
    forged = replace(contract, online=phase, contract_sha256="")
    forged = replace(
        forged, contract_sha256=_sha(_canonical(forged.binding_dict()))
    )
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(forged)
    assert raised.value.code in {
        "YARN_OPERATION_CONTRACT_INVALID",
        "WRITABLE_ROOT_ESCAPE",
        "PHASE_BINDING_INVALID",
    }
    assert not Path(forged.online.private_root).parent.exists()


def test_rehashed_aliasing_controller_mount_contract_is_rejected_before_mutation(
    tmp_path: Path,
) -> None:
    contract = _contract(tmp_path)
    execution_body = contract.execution.binding_dict()
    execution_body.pop("binding_sha256")
    execution_body["controller_state_root"] = execution_body[
        "controller_scratch_root"
    ]
    forged_execution = AUTH.GuestExecutionBinding(
        **execution_body,
        binding_sha256=_sha(_canonical(execution_body)),
    )
    forged = replace(
        contract,
        execution=forged_execution,
        contract_sha256="",
    )
    forged = replace(
        forged,
        contract_sha256=_sha(_canonical(forged.binding_dict())),
    )
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(forged)
    assert raised.value.code == "GUEST_EXECUTION_BINDING_INVALID"
    assert not Path(forged.execution.controller_transaction_root).exists()


def test_physical_state_to_scratch_alias_is_rejected_before_native_execution(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    transaction = Path(contract.execution.controller_transaction_root)
    transaction.mkdir(mode=0o700)
    marker_base = {
        "contract_sha256": contract.contract_sha256,
        "custody_receipt_sha256": _authorities().custody_receipt_sha256,
        "schema": RUNTIME.MARKER_SCHEMA,
    }
    marker = marker_base | {"marker_sha256": _sha(_canonical(marker_base))}
    marker_path = transaction / ".plamen-js-materializer-owner.json"
    marker_path.write_bytes(_canonical(marker) + b"\n")
    marker_path.chmod(0o400)
    scratch = Path(contract.execution.controller_scratch_root)
    scratch.mkdir(mode=0o700)
    os.symlink(scratch, contract.execution.controller_state_root)

    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code in {
        "CONTROLLER_MOUNT_ROOT_UNSAFE",
        "PATH_ALIAS_REJECTED",
    }
    assert fake.calls == []


def test_empty_modules_cannot_certify_nonempty_lock_closure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    fake.mutate = "empty-modules"
    _enable_fake(monkeypatch, fake)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "DEPENDENCY_TREE_EMPTY"


def test_exact_selector_replay_and_idempotent_terminal_receipt(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    first = _run(contract)
    second = _run(contract)
    assert fake.calls == list(RUNTIME._OPERATIONS)
    assert first.receipt_sha256 == second.receipt_sha256
    assert first.modules_root == contract.offline_replay.modules_root
    assert first.receipt["terminal_state"] == "OFFLINE_REPLAY_VERIFIED"
    assert first.receipt["lock_selection_sha256"] == contract.lock_selection.selection_sha256


def test_linux_guest_request_has_explicit_disjoint_mount_and_path_projection(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    result = _run(contract)
    assert result.receipt["guest_execution"]["guest_project_root"] == (
        "/workspace/project"
    )
    online = next(
        row for row in fake.requests if row["operation"] == "ONLINE_INSTALL"
    )
    assert online["schema"] == RUNTIME.REQUEST_SCHEMA
    assert online["guest_platform"] == {"arch": "x86_64", "os": "linux"}
    assert online["mounts"] == [
        {
            "access": "IMMUTABLE_READ_ONLY",
            "controller_path": contract.source_root,
            "guest_path": "/workspace/project",
            "role": "project",
        },
        {
            "access": "PRIVATE_READ_WRITE",
            "controller_path": contract.execution.controller_scratch_root,
            "guest_path": "/workspace/scratch",
            "role": "scratch",
        },
        {
            "access": "PRIVATE_READ_WRITE",
            "controller_path": contract.execution.controller_state_root,
            "guest_path": "/workspace/state",
            "role": "state",
        },
    ]
    assert online["guest_cwd"] == "/workspace/project"
    assert online["guest_argv"][0].startswith("/workspace/scratch/toolchain/")
    assert online["guest_outputs"]["modules"].startswith(
        "/workspace/scratch/online/"
    )
    assert online["network_policy"]["allowed_origins"] == [
        {"host": "registry.npmjs.org", "port": 443, "scheme": "https"},
        {"host": "registry.yarnpkg.com", "port": 443, "scheme": "https"},
    ]
    assert online["network_policy"]["dns_mode"] == (
        "NATIVE_BROKER_ALLOWLIST_ONLY"
    )
    assert online["network_policy"]["kind"] == (
        "EXACT_REACHABLE_LOCK_HTTPS_ORIGIN_ALLOWLIST"
    )
    rendered_guest = _canonical(
        {
            "argv": online["guest_argv"],
            "cwd": online["guest_cwd"],
            "environment": online["guest_environment"],
            "expected_inputs": online["guest_expected_inputs"],
            "outputs": online["guest_outputs"],
        }
    )
    assert str(tmp_path).encode() not in rendered_guest


@pytest.mark.parametrize(
    ("mutation", "codes"),
    [
        ("lock", {"FILE_DIGEST_MISMATCH", "LOCK_SELECTION_REPLAY_FAILED"}),
        ("source", {"SOURCE_CHANGED_DURING_MATERIALIZATION"}),
        ("symlink", {"OUTPUT_TREE_SPECIAL_FILE_REJECTED"}),
        ("hardlink", {"OUTPUT_TREE_HARDLINK_REJECTED"}),
        ("cache", {"CACHE_HANDOFF_NOT_BYTE_EXACT"}),
        ("toolchain", {"MATERIALIZED_TOOLCHAIN_CHANGED"}),
        ("integrity", {"YARN_INTEGRITY_LOCK_CLOSURE_MISMATCH"}),
        ("integrity-value", {"YARN_INTEGRITY_LOCK_CLOSURE_MISMATCH"}),
        ("package-version", {"INSTALLED_DIRECT_PACKAGE_IDENTITY_MISMATCH"}),
    ],
)
def test_adversarial_mutations_fail_closed(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    mutation: str,
    codes: set[str],
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    fake.mutate = mutation
    _enable_fake(monkeypatch, fake)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code in codes
    assert not (Path(contract.execution.controller_state_root) / "materialization.receipt.json").exists()


def test_online_only_success_cannot_commit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    fake.fail_operation = "OFFLINE_REPLAY"
    _enable_fake(monkeypatch, fake)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "NATIVE_MATERIALIZER_EXECUTION_FAILED"
    assert "ONLINE_INSTALL" in fake.calls
    assert not (Path(contract.execution.controller_state_root) / "materialization.receipt.json").exists()


@pytest.mark.parametrize("failure", ["network", "timeout"])
def test_offline_network_or_timeout_terminal_is_rejected(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    failure: str,
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    original = fake.execute

    def execute(capability: object, raw: bytes) -> bytes:
        terminal_raw = original(capability, raw)
        request = json.loads(raw)
        if request["operation"] != "OFFLINE_REPLAY":
            return terminal_raw
        terminal = json.loads(terminal_raw)
        if failure == "network":
            terminal["observed_egress_sha256"] = _sha(b"forbidden-egress")
        else:
            terminal["timed_out"] = True
        terminal.pop("terminal_receipt_sha256")
        terminal["terminal_receipt_sha256"] = _sha(_canonical(terminal))
        return _canonical(terminal) + b"\n"

    fake.execute = execute  # type: ignore[method-assign]
    _enable_fake(monkeypatch, fake)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code in {
        "OFFLINE_NETWORK_ACTIVITY_OBSERVED",
        "NATIVE_TERMINAL_AUTHORITY_INVALID",
    }


def test_online_terminal_must_report_exact_admitted_egress(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    original = fake.execute

    def execute(capability: object, raw: bytes) -> bytes:
        terminal_raw = original(capability, raw)
        request = json.loads(raw)
        if request["operation"] != "ONLINE_INSTALL":
            return terminal_raw
        terminal = json.loads(terminal_raw)
        terminal["observed_egress_origins"] = [
            {"host": "attacker.invalid", "port": 443, "scheme": "https"}
        ]
        terminal["observed_egress_sha256"] = RUNTIME._digest(
            terminal["observed_egress_origins"]
        )
        terminal.pop("terminal_receipt_sha256")
        terminal["terminal_receipt_sha256"] = _sha(_canonical(terminal))
        return _canonical(terminal) + b"\n"

    fake.execute = execute  # type: ignore[method-assign]
    _enable_fake(monkeypatch, fake)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "ONLINE_EGRESS_IDENTITY_MISMATCH"


def test_crash_resume_cleans_only_uncommitted_private_phase(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    fake.crash_once = "ONLINE_INSTALL"
    _enable_fake(monkeypatch, fake)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError):
        _run(contract)
    source_before = (Path(contract.source_root) / "package.json").read_bytes()
    result = _run(contract)
    assert result.receipt["terminal_state"] == "OFFLINE_REPLAY_VERIFIED"
    assert fake.calls.count("PREPARE_TOOLCHAIN") == 1
    assert fake.calls.count("ONLINE_INSTALL") == 2
    assert (Path(contract.source_root) / "package.json").read_bytes() == source_before


def test_rehashed_python_journal_cannot_forge_native_terminal_custody(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    _run(contract)
    journal_path = (
        Path(contract.execution.controller_state_root)
        / "materialization.journal.json"
    )
    journal = json.loads(journal_path.read_bytes())
    terminal = journal["native_receipts"]["ONLINE_INSTALL"]
    terminal["stdout_bytes"] = 1
    terminal["stdout_sha256"] = _sha(b"x")
    terminal.pop("terminal_receipt_sha256")
    terminal["terminal_receipt_sha256"] = _sha(_canonical(terminal))
    journal_path.write_bytes(_canonical(journal) + b"\n")

    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "NATIVE_TERMINAL_REPLAY_FAILED"


def test_committed_post_install_mutation_is_not_an_idempotent_success(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    result = _run(contract)
    (Path(result.modules_root) / "dependency" / "index.js").write_bytes(b"mutated")
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code in {
        "OFFLINE_REPLAY_TREE_MISMATCH",
        "NATIVE_OUTPUT_TREE_MISMATCH",
        "FINAL_RECEIPT_CONFLICT",
    }


def test_project_rc_and_late_lockfile_are_rejected_before_native_execution(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    (Path(contract.source_root) / ".yarnrc").write_text("--ignore-scripts false\n")
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "PROJECT_PACKAGE_MANAGER_CONFIG_REJECTED"
    assert fake.calls == []
    (Path(contract.source_root) / ".yarnrc").unlink()
    (Path(contract.source_root) / "npm-shrinkwrap.json").write_bytes(_stale_npm())
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code == "LOCKFILE_SET_CHANGED"
    assert fake.calls == []


@pytest.mark.parametrize("alias_kind", ["symlink", "hardlink"])
def test_source_lock_aliases_are_rejected_before_native_execution(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    alias_kind: str,
) -> None:
    contract = _contract(tmp_path)
    fake = FakeNative(contract)
    _enable_fake(monkeypatch, fake)
    lock = Path(contract.source_root) / "yarn.lock"
    retained = tmp_path / "retained-yarn.lock"
    retained.write_bytes(lock.read_bytes())
    lock.unlink()
    if alias_kind == "symlink":
        os.symlink(retained, lock)
    else:
        os.link(retained, lock)
    with pytest.raises(RUNTIME.JSDependencyRuntimeError) as raised:
        _run(contract)
    assert raised.value.code in {"FILE_ALIAS_REJECTED", "FILE_IDENTITY_UNSAFE"}
    assert fake.calls == []


def test_native_guest_js_projection_is_one_descriptor_bound_transaction(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    project = tmp_path / "projection-project"
    private = tmp_path / "projection-private"
    modules = private / "offline-modules"
    project.mkdir()
    private.mkdir()
    modules.mkdir()
    (project / "C.sol").write_text("contract C {}\n")
    (modules / "dependency").mkdir()
    receipt = {
        "schema": "plamen.js-dependency-materialization-receipt.v2",
        "receipt_sha256": "1" * 64,
    }
    dependency = RUNTIME.JSDependencyMaterializationResult(
        private_root=str(private),
        modules_root=str(modules),
        receipt_path=str(private / "materialization.receipt.json"),
        receipt_sha256="1" * 64,
        receipt=receipt,
    )
    monkeypatch.setattr(
        RUNTIME, "execute_native_guest_js_dependency_materialization",
        lambda *_args, **_kwargs: dependency,
    )
    native_authority = object()
    projection_authority = object()
    projection_receipt = _canonical({
        "schema": "plamen.private-analysis-projection-custody.v1",
    })
    lineage = _canonical({
        "schema": "plamen.evm-tool-materialization-lineage.v2",
    })
    import posix_backend_execution as runtime

    def commit(_runtime: object, **kwargs: object) -> object:
        assert _runtime is native_authority
        assert kwargs["dependency_materialization_receipt"] is receipt
        scratch_fd = int(kwargs["scratch_fd"])
        state_fd = int(kwargs["state_fd"])
        os.mkdir("analysis-workspace", 0o700, dir_fd=scratch_fd)
        descriptor = os.open(
            "materialization-lineage.json",
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o400,
            dir_fd=state_fd,
        )
        try:
            os.write(descriptor, lineage)
        finally:
            os.close(descriptor)
        return projection_authority

    workspace_path = (
        private / "evm-analysis-projection" / "scratch" / "analysis-workspace"
    )
    binding = _canonical({
        "descriptor_identity_sha256": "2" * 64,
        "projection_receipt_sha256": _sha(projection_receipt),
        "schema": "plamen.evm-analysis-projection-workspace-binding.v1",
        "workspace_path": str(workspace_path),
    })
    monkeypatch.setattr(runtime, "commit_native_guest_evm_analysis_projection", commit)
    monkeypatch.setattr(
        runtime, "project_native_guest_evm_analysis_projection_receipt",
        lambda *_args: projection_receipt,
    )
    monkeypatch.setattr(
        runtime, "project_native_guest_evm_analysis_projection_lineage",
        lambda *_args: lineage,
    )
    monkeypatch.setattr(
        runtime, "project_native_guest_evm_analysis_projection_workspace_binding",
        lambda *_args: binding,
    )
    source = AUTH.ImmutableJSSourceInputs(
        source_root=str(project),
        source_snapshot_sha256="3" * 64,
        package_json=b"{}\n",
        lockfiles=(),
    )
    workspace = AUTH.PrivateDependencyWorkspaceInputs(
        private_root=str(private), generation_id="generation-1",
        phase_timeout_seconds=30, max_dependency_entries=100,
        max_dependency_expanded_bytes=1024 * 1024,
        max_cache_expanded_bytes=1024 * 1024,
    )
    result = RUNTIME.execute_native_guest_js_and_evm_analysis_projection(
        source, workspace,
        repository_root=tmp_path,
        target_os="darwin",
        target_arch="arm64",
        native_runtime_authority=native_authority,
        original_source_scope_sha256="3" * 64,
    )
    assert result.native_projection_authority is projection_authority
    assert result.workspace_binding["workspace_path"] == str(workspace_path)
    assert Path(result.projection_receipt_path).read_bytes() == projection_receipt
    assert Path(result.materialization_lineage_path).read_bytes() == lineage
    assert not (project / "node_modules").exists()
