"""Focused tests for the out-of-tree JavaScript dependency contract."""

from __future__ import annotations

from dataclasses import replace
import base64
import hashlib
import json
import os
from pathlib import Path

import pytest

import js_dependency_materializer_authority as MATERIALIZER
import js_toolchain_authority as TOOLCHAIN


ROOT = Path(__file__).resolve().parents[1]
_ANCHOR_SHA256 = hashlib.sha256(
    (ROOT / TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH).read_bytes()
).hexdigest()
_SOURCE_CENSUS_SHA256 = hashlib.sha256(
    b"authenticated-materializer-test-source-census"
).hexdigest()
BOOTSTRAP_AUTHORITY = TOOLCHAIN.TrustedJSBootstrapAuthority(
    anchor_relative_path=TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH.as_posix(),
    anchor_sha256=_ANCHOR_SHA256,
    source_census_sha256=_SOURCE_CENSUS_SHA256,
    install_provenance_sha256=TOOLCHAIN.bootstrap_install_provenance_sha256(
        anchor_relative_path=TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH.as_posix(),
        anchor_sha256=_ANCHOR_SHA256,
        source_census_sha256=_SOURCE_CENSUS_SHA256,
        trust_boundary=TOOLCHAIN.BOOTSTRAP_TRUST_BOUNDARY,
    ),
    trust_boundary=TOOLCHAIN.BOOTSTRAP_TRUST_BOUNDARY,
)


@pytest.fixture(scope="session")
def _rendered_runtime_closure(
    tmp_path_factory: pytest.TempPathFactory,
) -> Path:
    closure = (
        tmp_path_factory.mktemp("js-materializer-closure")
        / "toolchain_runtime_closure.v1.json"
    )
    member_paths = {
        "scripts/js_dependency_materializer_authority.py",
        "scripts/js_dependency_materializer_runtime.py",
        "scripts/js_lock_authority.py",
        "scripts/js_toolchain_authority.py",
        TOOLCHAIN.BOOTSTRAP_RELATIVE_PATH.as_posix(),
        TOOLCHAIN.MANIFEST_RELATIVE_PATH.as_posix(),
    }
    policy = json.loads(
        (ROOT / TOOLCHAIN.MANIFEST_RELATIVE_PATH).read_text(encoding="utf-8")
    )
    member_paths.update(row["packaged_path"] for row in policy["artifacts"])
    assets = []
    for relative in sorted(member_paths):
        raw = (ROOT / relative).read_bytes()
        if relative.endswith(".py"):
            kind = "python-source"
            digest_mode = "utf8-lf-v1"
            canonical = raw.decode("utf-8").replace("\r\n", "\n").encode()
        elif relative.startswith("verification_policy/"):
            kind = "control"
            digest_mode = "utf8-lf-v1"
            canonical = raw.decode("utf-8").replace("\r\n", "\n").encode()
        else:
            kind = "runtime-data"
            digest_mode = "raw-v1"
            canonical = raw
        assets.append(
            {
                "digest_mode": digest_mode,
                "kind": kind,
                "path": relative,
                "sha256": hashlib.sha256(canonical).hexdigest(),
            }
        )
    closure_relative = TOOLCHAIN.RUNTIME_CLOSURE_RELATIVE_PATH.as_posix()
    payload = {
        "assets": assets,
        "derivation": "python-ast-typed-runtime-closure-v2",
        "entrypoints": ["scripts/js_toolchain_authority.py"],
        "files": sorted({*member_paths, closure_relative}),
        "manifest_control": {
            "kind": "control",
            "path": closure_relative,
        },
        "schema": TOOLCHAIN.RUNTIME_CLOSURE_SCHEMA,
    }
    closure.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
        newline="\n",
    )
    return closure


@pytest.fixture(autouse=True)
def _current_runtime_closure(
    _rendered_runtime_closure: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Use the current derivation until the release owner freezes its manifest."""

    original = TOOLCHAIN.load_authority_manifest

    def load(
        repository_root: object,
        *,
        bootstrap_authority: TOOLCHAIN.TrustedJSBootstrapAuthority,
    ) -> TOOLCHAIN.AuthorityManifest:
        assert bootstrap_authority == BOOTSTRAP_AUTHORITY
        return original(
            repository_root,
            bootstrap_authority=bootstrap_authority,
            runtime_closure_path=_rendered_runtime_closure,
        )

    monkeypatch.setattr(TOOLCHAIN, "load_authority_manifest", load)


def _integrity(value: str) -> str:
    return "sha512-" + base64.b64encode(
        hashlib.sha512(value.encode("ascii")).digest()
    ).decode("ascii")


def _package(*, manager: str | None = None) -> bytes:
    value: dict[str, object] = {
        "name": "fixture",
        "version": "1.0.0",
        "dependencies": {"dependency": "^1.0.0"},
    }
    if manager is not None:
        value["packageManager"] = manager
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()


def _yarn() -> bytes:
    return (
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
        "# yarn lockfile v1\n\n"
        '"dependency@^1.0.0":\n'
        '  version "1.2.3"\n'
        '  resolved "https://registry.yarnpkg.com/dependency/-/dependency-1.2.3.tgz"\n'
        f"  integrity {_integrity('dependency')}\n"
    ).encode()


def _npm() -> bytes:
    return (
        json.dumps(
            {
                "name": "fixture",
                "version": "1.0.0",
                "lockfileVersion": 3,
                "packages": {
                    "": {
                        "name": "fixture",
                        "version": "1.0.0",
                        "dependencies": {"dependency": "^1.0.0"},
                    }
                },
            },
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode()


def _source(
    *,
    root: str = "/audit/source",
    locks: tuple[tuple[str, bytes], ...] | None = None,
    manager: str | None = None,
) -> MATERIALIZER.ImmutableJSSourceInputs:
    return MATERIALIZER.ImmutableJSSourceInputs(
        source_root=root,
        source_snapshot_sha256=hashlib.sha256(b"snapshot").hexdigest(),
        package_json=_package(manager=manager),
        lockfiles=locks or (("yarn.lock", _yarn()),),
    )


def _workspace(
    *, root: str = "/private/dependencies"
) -> MATERIALIZER.PrivateDependencyWorkspaceInputs:
    return MATERIALIZER.PrivateDependencyWorkspaceInputs(
        private_root=root,
        generation_id="attempt-001",
        phase_timeout_seconds=900,
        max_dependency_entries=20_000,
        max_dependency_expanded_bytes=512 * 1024 * 1024,
        max_cache_expanded_bytes=512 * 1024 * 1024,
    )


def _enable_packaged_artifact_fixture(
    monkeypatch: pytest.MonkeyPatch,
    *,
    os_name: str = "darwin",
    arch: str = "arm64",
) -> None:
    authority = TOOLCHAIN.load_authority_manifest(
        ROOT,
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
    )
    node, yarn = TOOLCHAIN.select_artifacts(
        authority, os_name=os_name, arch=arch
    )
    monkeypatch.setattr(
        MATERIALIZER.TOOLCHAIN,
        "load_authority_manifest",
        lambda _root, *, bootstrap_authority: authority,
    )
    monkeypatch.setattr(
        MATERIALIZER.TOOLCHAIN,
        "require_packaged_artifacts",
        lambda *_args, **_kwargs: {
            node.artifact_id: Path("/reviewed/node.tar.gz"),
            yarn.artifact_id: Path("/reviewed/yarn.tar.gz"),
        },
    )


def _build(monkeypatch: pytest.MonkeyPatch):
    _enable_packaged_artifact_fixture(monkeypatch)
    return MATERIALIZER.build_js_dependency_materialization_contract(
        _source(),
        _workspace(),
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
        repository_root=ROOT,
        target_os="darwin",
        target_arch="arm64",
    )


def test_real_repository_baseline_reaches_plan_only_native_boundary(
    tmp_path: Path,
) -> None:
    private = tmp_path / "must-not-be-created"
    contract = MATERIALIZER.build_js_dependency_materialization_contract(
        _source(),
        _workspace(root=str(private)),
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
        repository_root=ROOT,
        target_os="darwin",
        target_arch="arm64",
    )
    assert contract.execution_state == "PLAN_ONLY_NATIVE_LIFECYCLE_REQUIRED"
    assert contract.toolchain.node_archive_path == str(
        ROOT
        / "runtime/toolchains/js/node/node-v24.20.0-darwin-arm64.tar.gz"
    )
    assert contract.toolchain.yarn_archive_path == str(
        ROOT / "runtime/toolchains/js/yarn/yarn-v1.22.22.tar.gz"
    )
    assert not private.exists()


def test_real_repository_linux_x86_64_reaches_fixed_guest_boundary(
    tmp_path: Path,
) -> None:
    private = tmp_path / "linux-materialization"
    contract = MATERIALIZER.build_js_dependency_materialization_contract(
        _source(),
        _workspace(root=str(private)),
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
        repository_root=ROOT,
        target_os="linux",
        target_arch="x86_64",
    )
    assert contract.toolchain.node_archive_path == str(
        ROOT / "runtime/toolchains/js/node/node-v24.20.0-linux-x64.tar.xz"
    )
    assert contract.execution.binding_dict() == {
        "binding_sha256": contract.execution.binding_sha256,
        "controller_scratch_root": str(private / "scratch"),
        "controller_state_root": str(private / "state"),
        "controller_transaction_root": str(private),
        "guest_project_root": "/workspace/project",
        "guest_scratch_root": "/workspace/scratch",
        "guest_state_root": "/workspace/state",
        "project_access": "IMMUTABLE_READ_ONLY",
        "scratch_access": "PRIVATE_READ_WRITE",
        "state_access": "PRIVATE_READ_WRITE",
        "target_arch": "x86_64",
        "target_os": "linux",
    }
    assert not private.exists()


def test_exact_online_then_clean_offline_replay_contract(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    contract = _build(monkeypatch)

    assert contract.source_access == "IMMUTABLE_READ_ONLY_SNAPSHOT"
    assert contract.workspace_access == "PRIVATE_EMPTY_OUT_OF_TREE"
    assert contract.execution_state == "PLAN_ONLY_NATIVE_LIFECYCLE_REQUIRED"
    assert contract.lock_selection.family == "yarn"
    authority = TOOLCHAIN.load_authority_manifest(
        ROOT,
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
    )
    yarn = authority.artifacts[-1]
    assert contract.toolchain.yarn_archive_sha256 == yarn.sha256
    assert contract.toolchain.yarn_archive_size == yarn.size
    assert contract.toolchain.upstream_verification_sha256 == (
        authority.upstream_verification_sha256
    )
    assert contract.online.cwd == contract.offline_replay.cwd == "/audit/source"
    assert contract.online.modules_root == (
        "/private/dependencies/scratch/online/modules"
    )
    assert contract.offline_replay.modules_root == (
        "/private/dependencies/scratch/offline-replay/modules"
    )
    assert contract.online.cache_root != contract.offline_replay.cache_root
    assert contract.replay.online_cache_root == contract.online.cache_root
    assert contract.replay.offline_cache_seed_root == (
        contract.offline_replay.cache_root
    )
    assert contract.replay.cache_handoff == (
        "COPY_VERIFIED_TREE_INTO_EMPTY_OFFLINE_CACHE"
    )
    assert ("cache_tree_sha256", "seed_cache_tree_sha256") in (
        contract.replay.required_receipt_equalities
    )
    assert "OFFLINE_NETWORK_DENIAL_REMAINED_ACTIVE" in (
        contract.replay.required_terminal_conditions
    )
    assert contract.online.network_mode == (
        "VERIFIED_EXACT_LOCK_ORIGIN_ALLOWLIST"
    )
    assert contract.online.egress_target_id == "yarn-classic-registry"
    assert contract.offline_replay.network_mode == "NO_NETWORK"
    assert contract.offline_replay.egress_target_id == ""
    assert contract.online.argv[-2:] == (
        "--registry",
        "https://registry.yarnpkg.com",
    )
    assert contract.offline_replay.argv[-1] == "--offline"
    assert "--ignore-scripts" in contract.online.argv
    assert "--frozen-lockfile" in contract.online.argv
    toolchain_binding = contract.toolchain.binding_dict()
    binding_sha256 = toolchain_binding.pop("binding_sha256")
    assert binding_sha256 == hashlib.sha256(
        json.dumps(
            toolchain_binding,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ).encode("ascii")
    ).hexdigest()
    assert contract.contract_sha256 == hashlib.sha256(
        json.dumps(
            contract.binding_dict(),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ).encode("ascii")
    ).hexdigest()


def test_no_modules_or_writable_root_can_land_in_audit_source(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    contract = _build(monkeypatch)
    for phase in (contract.online, contract.offline_replay):
        for path in (
            phase.private_root,
            phase.home_root,
            phase.modules_root,
            phase.cache_root,
            phase.temp_root,
        ):
            assert not path.startswith(contract.source_root + "/")
        assert "node_modules" not in phase.modules_root
        assert phase.modules_root.endswith("/modules")

    with pytest.raises(MATERIALIZER.JSDependencyMaterializationError) as raised:
        MATERIALIZER.build_js_dependency_materialization_contract(
            _source(),
            _workspace(root="/audit/source/node_modules"),
            bootstrap_authority=BOOTSTRAP_AUTHORITY,
            repository_root=ROOT,
            target_os="darwin",
            target_arch="arm64",
        )
    assert raised.value.code == "SOURCE_PRIVATE_ROOTS_OVERLAP"


def test_stale_npm_is_bound_but_yarn_is_unique(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _enable_packaged_artifact_fixture(monkeypatch)
    stale = _npm().replace(b'"^1.0.0"', b'"^9.0.0"')
    contract = MATERIALIZER.build_js_dependency_materialization_contract(
        _source(locks=(("package-lock.json", stale), ("yarn.lock", _yarn()))),
        _workspace(),
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
        repository_root=ROOT,
        target_os="darwin",
        target_arch="arm64",
    )
    assert contract.lock_selection.family == "yarn"
    assessments = {
        item.filename: item for item in contract.lock_selection.candidates
    }
    assert assessments["package-lock.json"].error_codes == (
        "NPM_ROOT_DEPENDENCIES_MISMATCH",
    )
    assert assessments["package-lock.json"].lockfile_sha256 == hashlib.sha256(
        stale
    ).hexdigest()


def test_declared_npm_never_falls_through_to_yarn_materializer(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    called = False

    def load(
        _root: object,
        *,
        bootstrap_authority: TOOLCHAIN.TrustedJSBootstrapAuthority,
    ) -> object:
        nonlocal called
        called = True
        raise AssertionError("toolchain must not be inspected")

    monkeypatch.setattr(MATERIALIZER.TOOLCHAIN, "load_authority_manifest", load)
    with pytest.raises(MATERIALIZER.JSDependencyMaterializationError) as raised:
        MATERIALIZER.build_js_dependency_materialization_contract(
            _source(locks=(("package-lock.json", _npm()),), manager="npm@10.0.0"),
            _workspace(),
            bootstrap_authority=BOOTSTRAP_AUTHORITY,
            repository_root=ROOT,
            target_os="darwin",
            target_arch="arm64",
        )
    assert raised.value.code == "JS_LOCK_FAMILY_NOT_IMPLEMENTED"
    assert called is False


@pytest.mark.parametrize(
    ("field", "value", "code"),
    [
        ("phase_timeout_seconds", 0, "PHASE_TIMEOUT_INVALID"),
        (
            "phase_timeout_seconds",
            MATERIALIZER.MAX_PHASE_TIMEOUT_SECONDS + 1,
            "PHASE_TIMEOUT_INVALID",
        ),
        ("max_dependency_entries", 0, "DEPENDENCY_ENTRY_BOUND_INVALID"),
        (
            "max_dependency_expanded_bytes",
            MATERIALIZER.MAX_DEPENDENCY_EXPANDED_BYTES + 1,
            "DEPENDENCY_BYTE_BOUND_INVALID",
        ),
        (
            "max_cache_expanded_bytes",
            MATERIALIZER.MAX_CACHE_EXPANDED_BYTES + 1,
            "CACHE_BYTE_BOUND_INVALID",
        ),
    ],
)
def test_all_resource_bounds_fail_closed_before_toolchain_inspection(
    monkeypatch: pytest.MonkeyPatch,
    field: str,
    value: int,
    code: str,
) -> None:
    monkeypatch.setattr(
        MATERIALIZER.TOOLCHAIN,
        "load_authority_manifest",
        lambda _root, *, bootstrap_authority: pytest.fail(
            "toolchain inspected after invalid bounds"
        ),
    )
    with pytest.raises(MATERIALIZER.JSDependencyMaterializationError) as raised:
        MATERIALIZER.build_js_dependency_materialization_contract(
            _source(),
            replace(_workspace(), **{field: value}),
            bootstrap_authority=BOOTSTRAP_AUTHORITY,
            repository_root=ROOT,
            target_os="darwin",
            target_arch="arm64",
        )
    assert raised.value.code == code


@pytest.mark.parametrize(
    "debt_code",
    [
        "PACKAGED_ARTIFACT_MISSING",
        "PACKAGED_ARTIFACT_SIZE_MISMATCH",
        "PACKAGED_ARTIFACT_DIGEST_MISMATCH",
    ],
)
def test_missing_or_unauthenticated_yarn_bytes_have_a_typed_failure(
    monkeypatch: pytest.MonkeyPatch,
    debt_code: str,
) -> None:
    authority = TOOLCHAIN.load_authority_manifest(
        ROOT,
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
    )
    node, yarn = TOOLCHAIN.select_artifacts(
        authority, os_name="darwin", arch="arm64"
    )
    debt = (
        TOOLCHAIN.PackagingDebt(
            yarn.artifact_id,
            debt_code,
            yarn.packaged_path,
        ),
    )
    monkeypatch.setattr(
        MATERIALIZER.TOOLCHAIN,
        "load_authority_manifest",
        lambda _root, *, bootstrap_authority: authority,
    )

    def unavailable(*_args: object, **_kwargs: object) -> object:
        raise TOOLCHAIN.JSToolchainPackagingError(debt)

    monkeypatch.setattr(
        MATERIALIZER.TOOLCHAIN, "require_packaged_artifacts", unavailable
    )
    with pytest.raises(MATERIALIZER.JSDependencyMaterializationError) as raised:
        MATERIALIZER.build_js_dependency_materialization_contract(
            _source(),
            _workspace(),
            bootstrap_authority=BOOTSTRAP_AUTHORITY,
            repository_root=ROOT,
            target_os="darwin",
            target_arch="arm64",
        )
    assert raised.value.code == "YARN_TOOLCHAIN_BYTES_UNAVAILABLE"
    assert raised.value.packaging_debt == debt
    assert node.artifact_id not in {item.artifact_id for item in debt}


def test_contract_values_and_nested_source_bytes_are_immutable(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    source = _source()
    with pytest.raises(Exception):
        source.source_root = "/attacker"  # type: ignore[misc]
    with pytest.raises(TypeError):
        source.lockfiles[0][1][0] = 0  # type: ignore[index]
    contract = _build(monkeypatch)
    with pytest.raises(Exception):
        contract.online.modules_root = (  # type: ignore[misc]
            "/audit/source/node_modules"
        )


def test_closed_environment_does_not_inherit_ambient_values(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("NODE_OPTIONS", "--require=/attacker.js")
    monkeypatch.setenv("YARN_CACHE_FOLDER", "/attacker-cache")
    monkeypatch.setenv("HTTPS_PROXY", "https://attacker.invalid")
    contract = _build(monkeypatch)
    for phase in (contract.online, contract.offline_replay):
        environment = dict(phase.environment)
        assert "NODE_OPTIONS" not in environment
        assert "HTTPS_PROXY" not in environment
        assert environment["YARN_CACHE_FOLDER"] == phase.cache_root
        assert os.environ["YARN_CACHE_FOLDER"] != phase.cache_root


def test_windows_contract_uses_only_absolute_private_paths(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _enable_packaged_artifact_fixture(
        monkeypatch, os_name="windows", arch="x86_64"
    )
    contract = MATERIALIZER.build_js_dependency_materialization_contract(
        _source(root=r"C:\audit\source"),
        _workspace(root=r"D:\private\dependencies"),
        bootstrap_authority=BOOTSTRAP_AUTHORITY,
        repository_root=ROOT,
        target_os="windows",
        target_arch="x86_64",
        windows_system_root=r"C:\Windows",
    )
    assert contract.online.cwd == r"C:\audit\source"
    assert contract.online.modules_root == (
        r"D:\private\dependencies\scratch\online\modules"
    )
    assert contract.offline_replay.argv[-1] == "--offline"
    assert dict(contract.online.environment)["SYSTEMROOT"] == r"C:\Windows"


def test_lockfile_input_shape_is_deeply_exact() -> None:
    malformed = replace(
        _source(),
        lockfiles=(("yarn.lock", _yarn()), ("yarn.lock", _yarn())),
    )
    with pytest.raises(MATERIALIZER.JSDependencyMaterializationError) as raised:
        MATERIALIZER.build_js_dependency_materialization_contract(
            malformed,
            _workspace(),
            bootstrap_authority=BOOTSTRAP_AUTHORITY,
            repository_root=ROOT,
            target_os="darwin",
            target_arch="arm64",
        )
    assert raised.value.code == "LOCKFILE_INPUTS_INVALID"
