from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path

import pytest

from js_lock_authority import (
    DECLARED_PACKAGE_MANAGER_LOCK,
    derive_yarn_integrity_authority,
    JSLockAuthorityError,
    select_js_lock_authority,
    UNIQUE_MANIFEST_CONSISTENT_LOCK,
)


def _package(
    dependencies: dict[str, str] | None = None,
    *,
    dev: dict[str, str] | None = None,
    optional: dict[str, str] | None = None,
    package_manager: str | None = None,
) -> bytes:
    value: dict[str, object] = {
        "name": "fixture",
        "version": "1.0.0",
        "dependencies": dependencies or {},
    }
    if dev is not None:
        value["devDependencies"] = dev
    if optional is not None:
        value["optionalDependencies"] = optional
    if package_manager is not None:
        value["packageManager"] = package_manager
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()


def _npm_lock(
    dependencies: dict[str, str] | None = None,
    *,
    dev: dict[str, str] | None = None,
    optional: dict[str, str] | None = None,
) -> bytes:
    root: dict[str, object] = {
        "name": "fixture",
        "version": "1.0.0",
    }
    if dependencies:
        root["dependencies"] = dependencies
    if dev:
        root["devDependencies"] = dev
    if optional:
        root["optionalDependencies"] = optional
    value = {
        "name": "fixture",
        "version": "1.0.0",
        "lockfileVersion": 3,
        "requires": True,
        "packages": {"": root},
    }
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()


def _integrity(seed: str) -> str:
    return "sha512-" + base64.b64encode(
        hashlib.sha512(seed.encode()).digest()
    ).decode("ascii")


def _entry(
    selectors: str | tuple[str, ...],
    *,
    version: str = "1.0.0",
    resolved: str | None = None,
    integrity: str | None = None,
    dependencies: dict[str, str] | None = None,
    optional: dict[str, str] | None = None,
) -> str:
    if isinstance(selectors, str):
        selectors = (selectors,)
    header = ", ".join(json.dumps(item) for item in selectors)
    identity = selectors[0].replace("/", "-").replace("@", "-")
    rows = [
        f"{header}:",
        f"  version {json.dumps(version)}",
    ]
    if resolved is not None:
        rows.append(f"  resolved {json.dumps(resolved)}")
    else:
        rows.append(
            f"  resolved {json.dumps(f'https://registry.example.invalid/{identity}.tgz')}"
        )
    if integrity is not None:
        rows.append(f"  integrity {integrity}")
    else:
        rows.append(f"  integrity {_integrity(identity)}")
    if dependencies:
        rows.append("  dependencies:")
        for name, spec in sorted(dependencies.items()):
            rows.append(f"    {json.dumps(name)} {json.dumps(spec)}")
    if optional:
        rows.append("  optionalDependencies:")
        for name, spec in sorted(optional.items()):
            rows.append(f"    {json.dumps(name)} {json.dumps(spec)}")
    return "\n".join(rows)


def _yarn(*entries: str) -> bytes:
    return (
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
        "# yarn lockfile v1\n\n"
        + "\n\n".join(entries)
        + "\n"
    ).encode()


def _error(code: str, package: bytes, locks: dict[str, bytes]) -> JSLockAuthorityError:
    with pytest.raises(JSLockAuthorityError) as caught:
        select_js_lock_authority(package, locks)
    assert caught.value.code == code
    return caught.value


def test_exact_npm_root_maps_select_npm() -> None:
    package = _package({"a": "^1"}, dev={"b": "2.0.0"})
    selected = select_js_lock_authority(
        package,
        {"package-lock.json": _npm_lock({"a": "^1"}, dev={"b": "2.0.0"})},
    )

    assert selected.family == "npm"
    assert selected.filename == "package-lock.json"
    assert selected.declared_package_manager == ""
    assert selected.candidates[0].consistent is True


def test_npm_root_extra_missing_and_changed_specs_are_inconsistent() -> None:
    package = _package({"a": "^1", "b": "^2"}, dev={"dev": "3"})
    error = _error(
        "NO_MANIFEST_CONSISTENT_LOCK",
        package,
        {
            "package-lock.json": _npm_lock(
                {"a": "^9", "extra": "1", "b": "^2"}
            )
        },
    )

    assert error.assessments[0].error_codes == (
        "NPM_ROOT_DEPENDENCIES_MISMATCH",
        "NPM_ROOT_DEVDEPENDENCIES_MISMATCH",
    )


def test_package_json_duplicate_key_is_rejected_before_lock_inspection() -> None:
    _error(
        "PACKAGE_JSON_DUPLICATE_KEY",
        b'{"dependencies":{"a":"^1","a":"^2"}}\n',
        {"yarn.lock": b"attacker bytes"},
    )


def test_package_json_conflicting_sections_are_rejected() -> None:
    _error(
        "PACKAGE_JSON_DEPENDENCY_CONFLICT",
        b'{"dependencies":{"a":"^1"},"devDependencies":{"a":"^2"}}\n',
        {"package-lock.json": _npm_lock({"a": "^1"})},
    )


def test_yarn_recursive_graph_and_grouped_selectors_select() -> None:
    package = _package({"a": "^1"})
    lock = _yarn(
        _entry("a@^1", dependencies={"b": "~2.0.0"}),
        _entry(("b@~2.0.0", "b@^2"), version="2.1.0"),
    )

    selected = select_js_lock_authority(package, {"yarn.lock": lock})

    assert selected.family == "yarn"
    assert selected.selection_basis == UNIQUE_MANIFEST_CONSISTENT_LOCK
    assert selected.reachable_stanza_count == 2
    assert selected.unused_stanza_count == 0

    integrity = derive_yarn_integrity_authority(package, lock, selected)
    assert integrity.lockfile_entries == (
        ("a@^1", "https://registry.example.invalid/a-^1.tgz"),
        ("b@^2", "https://registry.example.invalid/b-~2.0.0.tgz"),
        ("b@~2.0.0", "https://registry.example.invalid/b-~2.0.0.tgz"),
    )
    assert integrity.direct_packages == (("a", "a@^1", "1.0.0"),)


def test_yarn_integrity_authority_binds_resolved_values_not_only_keys() -> None:
    package = _package({"a": "^1"})
    first_lock = _yarn(_entry("a@^1"))
    second_lock = _yarn(
        _entry(
            "a@^1",
            resolved="https://registry.yarnpkg.com/a/-/alternate-a-1.0.0.tgz",
        )
    )
    first_selection = select_js_lock_authority(package, {"yarn.lock": first_lock})
    second_selection = select_js_lock_authority(package, {"yarn.lock": second_lock})
    first = derive_yarn_integrity_authority(package, first_lock, first_selection)
    second = derive_yarn_integrity_authority(package, second_lock, second_selection)
    assert first.lockfile_entries[0][0] == second.lockfile_entries[0][0]
    assert first.lockfile_entries[0][1] != second.lockfile_entries[0][1]
    assert first.lockfile_entries_sha256 != second.lockfile_entries_sha256
    assert first.authority_sha256 != second.authority_sha256


@pytest.mark.parametrize(
    ("lock", "candidate_code"),
    [
        (b"# not yarn v1\n", "YARN_LOCK_V1_HEADER_REQUIRED"),
        (
            _yarn(_entry("a@^1"), _entry("a@^1", version="1.1.0")),
            "YARN_LOCK_DUPLICATE_SELECTOR",
        ),
        (
            _yarn(_entry("a@^1", dependencies={"missing": "^2"})),
            "YARN_LOCK_REACHABLE_SELECTOR_MISSING",
        ),
        (
            _yarn(_entry("a@^1", resolved="http://registry.example/a.tgz")),
            "YARN_LOCK_RESOLVED_NOT_SAFE_HTTPS",
        ),
        (
            _yarn(_entry("a@^1", resolved="https://user:secret@registry.example/a.tgz")),
            "YARN_LOCK_RESOLVED_NOT_SAFE_HTTPS",
        ),
        (
            _yarn(_entry("a@^1", integrity="sha1-AAAAAAAAAAAAAAAAAAAAAAAAAAA=")),
            "YARN_LOCK_INTEGRITY_ALGORITHM_UNSUPPORTED",
        ),
    ],
)
def test_yarn_adversarial_candidate_failures_have_exact_codes(
    lock: bytes, candidate_code: str
) -> None:
    error = _error(
        "NO_MANIFEST_CONSISTENT_LOCK", _package({"a": "^1"}), {"yarn.lock": lock}
    )
    assert error.assessments[0].error_codes == (candidate_code,)


def test_yarn_direct_selector_must_match_exact_manifest_specifier() -> None:
    error = _error(
        "NO_MANIFEST_CONSISTENT_LOCK",
        _package({"a": "^1.2.0"}),
        {"yarn.lock": _yarn(_entry("a@^1.0.0"))},
    )
    assert error.assessments[0].error_codes == (
        "YARN_LOCK_DIRECT_SELECTOR_MISSING",
    )


@pytest.mark.parametrize("specifier", ["file:../a", "link:../a", "git+https://example/a.git", "https://example/a.tgz"])
def test_yarn_reachable_exotic_protocols_are_rejected(specifier: str) -> None:
    error = _error(
        "NO_MANIFEST_CONSISTENT_LOCK",
        _package({"a": specifier}),
        {"yarn.lock": _yarn(_entry(f"a@{specifier}"))},
    )
    assert error.assessments[0].error_codes == (
        "YARN_LOCK_UNSUPPORTED_PROTOCOL",
    )


def test_declared_manager_is_authoritative_and_never_falls_back() -> None:
    package = _package({"a": "^1"}, package_manager="yarn@1.22.22")
    error = _error(
        "DECLARED_LOCK_INCONSISTENT",
        package,
        {
            "package-lock.json": _npm_lock({"a": "^1"}),
            "yarn.lock": _yarn(_entry("other@^1")),
        },
    )

    assessments = {item.family: item for item in error.assessments}
    assert assessments["npm"].consistent is True
    assert assessments["yarn"].consistent is False


def test_declared_manager_requires_its_lock_even_when_another_is_valid() -> None:
    _error(
        "DECLARED_LOCK_MISSING",
        _package({"a": "^1"}, package_manager="yarn@1.22.22"),
        {"package-lock.json": _npm_lock({"a": "^1"})},
    )


def test_declared_manager_selection_basis_is_explicitly_bound() -> None:
    package = _package({"a": "^1"}, package_manager="yarn@1.22.22")
    selected = select_js_lock_authority(
        package, {"yarn.lock": _yarn(_entry("a@^1"))}
    )
    assert selected.selection_basis == DECLARED_PACKAGE_MANAGER_LOCK
    assert selected.binding_dict()["selection_basis"] == (
        DECLARED_PACKAGE_MANAGER_LOCK
    )


def test_undeclared_two_consistent_locks_remain_ambiguous() -> None:
    error = _error(
        "AMBIGUOUS_MANIFEST_CONSISTENT_LOCKS",
        _package({"a": "^1"}),
        {
            "package-lock.json": _npm_lock({"a": "^1"}),
            "yarn.lock": _yarn(_entry("a@^1")),
        },
    )
    assert [item.consistent for item in error.assessments] == [True, True]


def test_unsupported_family_prevents_false_unique_selection() -> None:
    _error(
        "UNSUPPORTED_LOCK_FAMILY_PRESENT",
        _package({"a": "^1"}),
        {
            "pnpm-lock.yaml": b"lockfileVersion: '9.0'\n",
            "yarn.lock": _yarn(_entry("a@^1")),
        },
    )


def test_unused_stanza_is_bound_but_is_not_selection_evidence() -> None:
    package = _package({"a": "^1"})
    first = select_js_lock_authority(
        package,
        {
            "yarn.lock": _yarn(
                _entry("a@^1"),
                _entry(
                    "unused@^7",
                    version="7.0.0",
                    resolved="http://unused.invalid/not-fetched.tgz",
                    integrity="sha1-AAAAAAAAAAAAAAAAAAAAAAAAAAA=",
                ),
            )
        },
    )
    second = select_js_lock_authority(
        package,
        {
            "yarn.lock": _yarn(
                _entry("a@^1"),
                _entry(
                    "unused@^8",
                    version="8.0.0",
                    resolved="http://unused.invalid/still-not-fetched.tgz",
                    integrity="sha1-AAAAAAAAAAAAAAAAAAAAAAAAAAA=",
                ),
            )
        },
    )

    assert first.family == second.family == "yarn"
    assert first.reachable_selectors_sha256 == second.reachable_selectors_sha256
    assert first.unused_stanza_count == second.unused_stanza_count == 1
    assert first.unused_selectors_sha256 != second.unused_selectors_sha256
    assert first.lockfile_sha256 != second.lockfile_sha256
    assert first.selection_sha256 != second.selection_sha256


def test_optional_dependency_is_part_of_recursive_reachability() -> None:
    package = _package({"a": "^1"})
    lock = _yarn(
        _entry("a@^1", optional={"optional-child": "^2"}),
        _entry("optional-child@^2", version="2.0.0"),
    )
    selected = select_js_lock_authority(package, {"yarn.lock": lock})
    assert selected.reachable_stanza_count == 2


def test_selection_digest_binds_rejected_stale_lockfile() -> None:
    package = _package({"a": "^1"})
    yarn = _yarn(_entry("a@^1"))
    first = select_js_lock_authority(
        package,
        {"package-lock.json": _npm_lock({"stale": "1"}), "yarn.lock": yarn},
    )
    second = select_js_lock_authority(
        package,
        {"package-lock.json": _npm_lock({"older": "1"}), "yarn.lock": yarn},
    )
    assert first.lockfile_sha256 == second.lockfile_sha256
    assert first.selection_sha256 != second.selection_sha256


def test_dodo_exact_files_select_yarn_and_reject_stale_npm() -> None:
    root = Path.home() / "dodo-cross-chain-dex" / "omni-chain-contracts"
    required = [root / "package.json", root / "package-lock.json", root / "yarn.lock"]
    if not all(path.is_file() for path in required):
        pytest.skip("DODO exact-file fixture is not present in this workspace")

    package = required[0].read_bytes()
    npm_lock = required[1].read_bytes()
    yarn_lock = required[2].read_bytes()
    assert hashlib.sha256(package).hexdigest() == (
        "2b061d9012f97f7d6b56ccb40236dc99eee8a85bce01671028a35a08d2c63b0f"
    )
    assert hashlib.sha256(npm_lock).hexdigest() == (
        "0a35d032bb44f4d1d2b236827c1620f76c000fd0c394125cec948ba034d66f82"
    )
    assert hashlib.sha256(yarn_lock).hexdigest() == (
        "7fe1da772063122c6fb581fafb1851d663fc41d380abebaef5e44159e778313b"
    )

    selected = select_js_lock_authority(
        package,
        {"package-lock.json": npm_lock, "yarn.lock": yarn_lock},
    )

    assert selected.family == "yarn"
    assert selected.filename == "yarn.lock"
    assert selected.selection_basis == UNIQUE_MANIFEST_CONSISTENT_LOCK
    assert selected.reachable_stanza_count == 1065
    assert selected.unused_stanza_count == 0
    assessments = {item.filename: item for item in selected.candidates}
    assert assessments["yarn.lock"].consistent is True
    assert assessments["package-lock.json"].consistent is False
    assert assessments["package-lock.json"].error_codes == (
        "NPM_ROOT_DEPENDENCIES_MISMATCH",
        "NPM_ROOT_DEVDEPENDENCIES_MISMATCH",
    )
    integrity = derive_yarn_integrity_authority(package, yarn_lock, selected)
    assert len(integrity.lockfile_entries) == 1386
    assert len(integrity.direct_packages) == 48
    assert integrity.lockfile_entries_sha256 == (
        "f291caa6a9d988d5c3c7aa7287fd636fdf52eb83954a092ed12d9242b217c635"
    )
    assert integrity.resolved_origins == (
        ("https", "registry.npmjs.org", 443),
        ("https", "registry.yarnpkg.com", 443),
    )
    assert integrity.resolved_origins_sha256 == (
        "b962c381f159f4daf8e4fa325dfe79c102b842d12cb61379975a0db6657efe7a"
    )
    assert integrity.authority_sha256 == (
        "a20581111e1286a57359e45a33bbb2eb31383dfe3797a7e2f974f508f58107c6"
    )
